In [1]:
import pandas as pd
import geopandas as gpd

In [ ]:
#día
lds_clima_1= gpd.read_file("../../data/mediciones_clima/LDS_clima.geojson")
rdp_m_clima_1= gpd.read_file("../../data/mediciones_clima/RDP-MONTES_clima.geojson")
rn_upm1_clima_1= gpd.read_file("../../data/mediciones_clima/RN-UPM1_clima.geojson")
rn_upm2_clima_1= gpd.read_file("../../data/mediciones_clima/RN-UPM2_clima.geojson")

In [11]:
#2días
lds_clima_2= gpd.read_file("../../data/mediciones_clima/LDS_clima_48.geojson")
rdp_m_clima_2= gpd.read_file("../../data/mediciones_clima/RDP-MONTES_clima_48.geojson")
rn_upm1_clima_2= gpd.read_file("../../data/mediciones_clima/RN-UPM1_clima_48.geojson")
rn_upm2_clima_2= gpd.read_file("../../data/mediciones_clima/RN-UPM2_clima_48.geojson")

In [ ]:
#dataset: 
data_set = pd.read_csv("../../data/dataset_final/indices_acolite.csv")

In [ ]:
print(lds_clima_1.shape)
print(rdp_m_clima_1.shape)
print(rn_upm1_clima_1.shape)
print(rn_upm2_clima_1.shape)

(1140, 16)
(363, 16)
(172, 16)
(1386, 16)

In [ ]:
clima_1 = pd.concat([lds_clima_1, rdp_m_clima_1, rn_upm1_clima_1, rn_upm2_clima_1], ignore_index=True)
clima_1.shape

(3061, 16)

In [18]:
clima_1

,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,dia,nombre,fecha_inicio,temperatura_maxima,temperatura_minima,pluviometro,granularidad,año,geometry
0,2017-01-02 00:00:00,GEMS,6.8,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,2017-01-02,Las Brujas,2017-01-02 09:00:00,28.5,18.6,0.0,DIA,2017,POINT (678380.002 6147956.963)
1,2017-01-02 00:00:00,GEMS,3.2,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,2017-01-02,Las Brujas,2017-01-02 09:00:00,28.5,18.6,0.0,DIA,2017,POINT (679045.962 6144090.994)
2,2017-01-02 00:00:00,GEMS,5.9,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,2017-01-02,Las Brujas,2017-01-02 09:00:00,28.5,18.6,0.0,DIA,2017,POINT (676618.974 6142887.026)
3,2017-01-02 00:00:00,GEMS,11.4,LDS,M,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,2017-01-02,Las Brujas,2017-01-02 09:00:00,28.5,18.6,0.0,DIA,2017,POINT (669756.975 6142832.05)
4,2017-01-02 00:00:00,GEMS,5.9,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,2017-01-02,Las Brujas,2017-01-02 09:00:00,28.5,18.6,0.0,DIA,2017,POINT (675890.225 6151378.242)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3056,2026-05-06 15:14:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 01:31:38.976000,2026-05-06,Tacuarembo,2026-05-06 09:00:00,29.8,19.2,0.0,DIA,2026,POINT (540411.19 6365961.336)
3057,2026-05-06 15:28:00,OAN,3.0,RN-UPM2,O,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 01:45:38.976000,2026-05-06,Tacuarembo,2026-05-06 09:00:00,29.8,19.2,0.0,DIA,2026,POINT (540435.203 6366112.119)
3058,2026-05-06 15:50:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:07:38.976000,2026-05-06,Tacuarembo,2026-05-06 09:00:00,29.8,19.2,0.0,DIA,2026,POINT (540534.657 6366265.697)
3059,2026-05-06 16:05:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:22:38.976000,2026-05-06,Tacuarembo,2026-05-06 09:00:00,29.8,19.2,0.0,DIA,2026,POINT (541076.43 6365906.268)
3060,2026-05-06 16:25:00,OAN,3.0,RN-UPM2,O,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:42:38.976000,2026-05-06,Tacuarembo,2026-05-06 09:00:00,29.8,19.2,0.0,DIA,2026,POINT (541711.453 6366698.147)

In [ ]:
clima_1.groupby("grupo_nombre").size()

grupo_nombre
LDS           1140
RDP-MONTES     363
RN-UPM1        172
RN-UPM2       1386
dtype: int64

In [ ]:
data_set_gdf = gpd.GeoDataFrame(data_set, geometry=gpd.points_from_xy(data_set["lon"], data_set["lat"]), crs="EPSG:4326")
data_set_gdf.head()

(2957, 61)
EPSG:4326

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos,geometry
0,0,2017-01-02 00:00:00,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.072809,-34.20507599999999,...,,,,,,,,False,True,POINT (-58.07281 -34.20508)
1,1,2017-01-02 00:00:00,GEMS,6.800000090152,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.050169,-34.795007999999996,...,0.9142366647720337,0.020905494689941406,0.015930041670799255,0.011604350060224533,0.011687852442264557,0.0008580870926380157,0.000585055910050869,False,False,POINT (-55.05017 -34.79501)
2,2,2017-01-02 00:00:00,GEMS,3.1999999191612,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.042069,-34.829733,...,0.9047808647155762,0.018550515174865723,0.016533222049474716,0.01062911469489336,0.010657023638486862,0.0014560222625732422,0.0008662490290589631,False,False,POINT (-55.04207 -34.82973)
3,3,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.06169100000001,-34.242903999999996,...,,,,,,,,False,True,POINT (-58.06169 -34.2429)
4,4,2017-01-02 00:00:00,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.068754,-34.21919799999999,...,,,,,,,,False,True,POINT (-58.06875 -34.2192)

In [20]:
data_set_gdf["dia"] = pd.to_datetime(data_set_gdf["fecha"]).dt.normalize()
data_set_gdf

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos,geometry,dia
0,0,2017-01-02 00:00:00,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.072809,-34.20507599999999,...,,,,,,,False,True,POINT (-58.07281 -34.20508),2017-01-02
1,1,2017-01-02 00:00:00,GEMS,6.800000090152,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.050169,-34.795007999999996,...,0.020905494689941406,0.015930041670799255,0.011604350060224533,0.011687852442264557,0.0008580870926380157,0.000585055910050869,False,False,POINT (-55.05017 -34.79501),2017-01-02
2,2,2017-01-02 00:00:00,GEMS,3.1999999191612,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.042069,-34.829733,...,0.018550515174865723,0.016533222049474716,0.01062911469489336,0.010657023638486862,0.0014560222625732422,0.0008662490290589631,False,False,POINT (-55.04207 -34.82973),2017-01-02
3,3,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.06169100000001,-34.242903999999996,...,,,,,,,False,True,POINT (-58.06169 -34.2429),2017-01-02
4,4,2017-01-02 00:00:00,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.068754,-34.21919799999999,...,,,,,,,False,True,POINT (-58.06875 -34.2192),2017-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952,2952,2026-05-06 15:14:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 01:31:39,-56.568167,-32.843666999999996,...,,,,,,,False,True,POINT (-56.56817 -32.84367),2026-05-06
2953,2953,2026-05-06 15:28:00,OAN,3.0,RN-UPM2,O,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 01:45:39,-56.567917,-32.842305999999994,...,0.0509263277053833,0.03751399740576744,0.0021602108608931303,0.0022756215184926987,0.0017361808568239212,0.0012578003806993365,False,False,POINT (-56.56792 -32.84231),2026-05-06
2954,2954,2026-05-06 15:50:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:07:39,-56.566861,-32.84091699999999,...,0.2896190285682678,0.3518015146255493,-0.00573617173358798,-0.0017445459961891174,0.008702603168785572,0.00813231710344553,False,False,POINT (-56.56686 -32.84092),2026-05-06
2955,2955,2026-05-06 16:05:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:22:39,-56.561056,-32.844139,...,,,,,,,False,True,POINT (-56.56106 -32.84414),2026-05-06
2956,2956,2026-05-06 16:25:00,OAN,3.0,RN-UPM2,O,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:42:39,-56.554306,-32.836972,...,,,,,,,False,True,POINT (-56.55431 -32.83697),2026-05-06

In [21]:
clima_1_sel = clima_1[["grupo_nombre", "dia", "nombre", "temperatura_minima", "temperatura_maxima", "pluviometro"]].drop_duplicates()
clima_1_sel.shape

(656, 6)

In [ ]:
data_set_clima = data_set_gdf.merge(clima_1_sel, left_on=["grupo_nombre", "dia"], right_on=["grupo_nombre", "dia"], how="left")
data_set_clima[["fecha", "dia", "grupo_nombre", "nombre", "temperatura_minima", "temperatura_maxima", "pluviometro"]].head()

(2957, 66)

,fecha,dia,grupo_nombre,nombre,temperatura_minima,temperatura_maxima,pluviometro
0,2017-01-02 00:00:00,2017-01-02,RDP-MONTES,La Estanzuela,20.6,29.7,0.0
1,2017-01-02 00:00:00,2017-01-02,LDS,Las Brujas,18.6,28.5,0.0
2,2017-01-02 00:00:00,2017-01-02,LDS,Las Brujas,18.6,28.5,0.0
3,2017-01-02 00:00:00,2017-01-02,RDP-MONTES,La Estanzuela,20.6,29.7,0.0
4,2017-01-02 00:00:00,2017-01-02,RDP-MONTES,La Estanzuela,20.6,29.7,0.0

In [24]:
data_set_clima[["nombre", "temperatura_minima", "temperatura_maxima", "pluviometro"]].isna().sum()

nombre                0
temperatura_minima    0
temperatura_maxima    0
pluviometro           0
dtype: int64

In [25]:
data_set_clima

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos,geometry,dia,nombre,temperatura_minima,temperatura_maxima,pluviometro
0,0,2017-01-02 00:00:00,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.072809,-34.20507599999999,...,,,False,True,POINT (-58.07281 -34.20508),2017-01-02,La Estanzuela,20.6,29.7,0.0
1,1,2017-01-02 00:00:00,GEMS,6.800000090152,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.050169,-34.795007999999996,...,0.0008580870926380157,0.000585055910050869,False,False,POINT (-55.05017 -34.79501),2017-01-02,Las Brujas,18.6,28.5,0.0
2,2,2017-01-02 00:00:00,GEMS,3.1999999191612,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.042069,-34.829733,...,0.0014560222625732422,0.0008662490290589631,False,False,POINT (-55.04207 -34.82973),2017-01-02,Las Brujas,18.6,28.5,0.0
3,3,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.06169100000001,-34.242903999999996,...,,,False,True,POINT (-58.06169 -34.2429),2017-01-02,La Estanzuela,20.6,29.7,0.0
4,4,2017-01-02 00:00:00,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.068754,-34.21919799999999,...,,,False,True,POINT (-58.06875 -34.2192),2017-01-02,La Estanzuela,20.6,29.7,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952,2952,2026-05-06 15:14:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 01:31:39,-56.568167,-32.843666999999996,...,,,False,True,POINT (-56.56817 -32.84367),2026-05-06,Tacuarembo,19.2,29.8,0.0
2953,2953,2026-05-06 15:28:00,OAN,3.0,RN-UPM2,O,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 01:45:39,-56.567917,-32.842305999999994,...,0.0017361808568239212,0.0012578003806993365,False,False,POINT (-56.56792 -32.84231),2026-05-06,Tacuarembo,19.2,29.8,0.0
2954,2954,2026-05-06 15:50:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:07:39,-56.566861,-32.84091699999999,...,0.008702603168785572,0.00813231710344553,False,False,POINT (-56.56686 -32.84092),2026-05-06,Tacuarembo,19.2,29.8,0.0
2955,2955,2026-05-06 16:05:00,OAN,1.5,RN-UPM2,U,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:22:39,-56.561056,-32.844139,...,,,False,True,POINT (-56.56106 -32.84414),2026-05-06,Tacuarembo,19.2,29.8,0.0
2956,2956,2026-05-06 16:25:00,OAN,3.0,RN-UPM2,O,S2A_MSIL1C_20260506T134221_N0512_R124_T21HWD_2...,0 days 02:42:39,-56.554306,-32.836972,...,,,False,True,POINT (-56.55431 -32.83697),2026-05-06,Tacuarembo,19.2,29.8,0.0


2 días

In [26]:
print(lds_clima_2.shape)
print(rdp_m_clima_2.shape)
print(rn_upm1_clima_2.shape)
print(rn_upm2_clima_2.shape)

(1140, 23)
(363, 23)
(172, 23)
(1386, 23)

In [27]:
clima_2 = pd.concat([lds_clima_2, rdp_m_clima_2, rn_upm1_clima_2, rn_upm2_clima_2], ignore_index=True)
clima_2.shape

(3061, 23)

In [28]:
clima_2.groupby("grupo_nombre").size()

grupo_nombre
LDS           1140
RDP-MONTES     363
RN-UPM1        172
RN-UPM2       1386
dtype: int64

In [29]:
clima_2_sel = clima_2[["grupo_nombre", "dia", "nombre", "temperatura_minima_48", "temperatura_maxima_48", "pluviometro_48"]].drop_duplicates()
clima_2_sel.shape

(656, 6)

In [ ]:
data_set_clima_2 = data_set_gdf.merge(clima_2_sel, left_on=["grupo_nombre", "dia"], right_on=["grupo_nombre", "dia"], how="left")
data_set_clima_2[["fecha", "dia", "grupo_nombre", "nombre", "temperatura_minima_48", "temperatura_maxima_48", "pluviometro_48"]].head()

(2957, 66)

,fecha,dia,grupo_nombre,nombre,temperatura_minima_48,temperatura_maxima_48,pluviometro_48
0,2017-01-02 00:00:00,2017-01-02,RDP-MONTES,La Estanzuela,22.9,31.05,0.0
1,2017-01-02 00:00:00,2017-01-02,LDS,Las Brujas,20.8,29.65,0.0
2,2017-01-02 00:00:00,2017-01-02,LDS,Las Brujas,20.8,29.65,0.0
3,2017-01-02 00:00:00,2017-01-02,RDP-MONTES,La Estanzuela,22.9,31.05,0.0
4,2017-01-02 00:00:00,2017-01-02,RDP-MONTES,La Estanzuela,22.9,31.05,0.0

In [31]:
data_set_clima_2[["nombre", "temperatura_minima_48", "temperatura_maxima_48", "pluviometro_48"]].isna().sum()

nombre                   0
temperatura_minima_48    0
temperatura_maxima_48    0
pluviometro_48           0
dtype: int64