In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
oan = gpd.read_file("../data/data/oan/oan_registros_clean.geojson")
chla_gems = gpd.read_file("../data/data/joins/gems_chla.geojson")
gem_puntos_examin = pd.read_csv("../data/data/puntos_examinados.csv")

In [3]:
oan["fuente"] = "OAN"
chla_gems ["fuente"] = "GEMS"
oan = oan.rename(columns={"fecha_hora": "fecha"})

In [3]:
oan["fuente"] = "OAN"
chla_gems["fuente"] = "GEMS"

In [4]:
oan = oan.rename(columns={"fecha_hora": "fecha"})

In [4]:
gem_puntos_examin.head()

,nombre,Decision,Fecha,Width,Resolution,geometry
0,URY00006,si,2025-02-13 13:52:11.656000,0.05,10,POINT (-55.3727 -34.5071)
1,URY00007,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2762 -34.391)
2,URY00008,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2061 -34.4204)
3,URY00009,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2471 -34.3791)
4,URY00010,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2317 -34.3828)

,nombre,Decision,Fecha,Width,Resolution,geometry
0,URY00006,si,2025-02-13 13:52:11.656000,0.05,10,POINT (-55.3727 -34.5071)
1,URY00007,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2762 -34.391)
2,URY00008,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2061 -34.4204)
3,URY00009,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2471 -34.3791)
4,URY00010,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2317 -34.3828)

In [6]:
chla_gems.shape

(3796, 10)

In [5]:
chla_gems = chla_gems[pd.to_datetime(chla_gems["fecha"]).dt.year >= 2017]
chla_gems["fecha"].min()

Timestamp('2017-01-02 00:00:00')

Timestamp('2017-01-02 00:00:00')

In [6]:
oan_utm  = oan.to_crs(32721).copy()
gems_utm = chla_gems.to_crs(32721).copy()

In [7]:
#oan_est  = oan_utm[['x','y','id_estacion']].drop_duplicates()
#gems_est = gems_utm[['x','y','estacion' ]].drop_duplicates()
#
#pares = gems_est.merge(oan_est, on=['x','y'], how='inner')
#
#print(len(pares), 'estaciones que coinciden')

In [10]:
oan.head()

,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,geometry,fuente
0,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29873.0,RÍO NEGRO,2019-09-05 16:00:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
1,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29985.0,RÍO NEGRO,2019-10-31 09:40:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
2,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31062.0,RÍO NEGRO,2020-06-04 14:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,POINT (-57.41304 -32.9058),OAN
3,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31410.0,RÍO NEGRO,2020-08-06 12:46:00,CloA_(lab),µg/L,33.000000000,0.700000000,2.2,33.000000000,POINT (-57.41304 -32.9058),OAN
4,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31851.0,RÍO NEGRO,2020-11-19 12:29:00,CloA_(lab),µg/L,2.600000000,0.700000000,2.2,2.600000000,POINT (-57.41304 -32.9058),OAN

In [8]:
oan_utm.head()
casos = ["<0.1", "<0.5", "<1", "<1.0", "<1.00", "<LC", "<LD", "LD<X<LC", "LD<x<LC"]
datos = oan[oan["valor_transformado"].isin(casos)]
#puntos_upm2 = OAN_registros_clean[OAN_registros_clean["nombre_programa_x"] == "Agua UPM2 Empresa"]

,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,geometry,fuente
0,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29873.0,RÍO NEGRO,2019-09-05 16:00:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (461374.621 6359080.918),OAN
1,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29985.0,RÍO NEGRO,2019-10-31 09:40:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (461374.621 6359080.918),OAN
2,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31062.0,RÍO NEGRO,2020-06-04 14:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,POINT (461374.621 6359080.918),OAN
3,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31410.0,RÍO NEGRO,2020-08-06 12:46:00,CloA_(lab),µg/L,33.000000000,0.700000000,2.2,33.000000000,POINT (461374.621 6359080.918),OAN
4,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31851.0,RÍO NEGRO,2020-11-19 12:29:00,CloA_(lab),µg/L,2.600000000,0.700000000,2.2,2.600000000,POINT (461374.621 6359080.918),OAN

In [12]:
datos.shape

(1795, 14)

In [13]:
for  valor in sorted(oan["valor_transformado"].unique(), key=str):
    print(valor)

0.000
0.100
0.100000000
0.200000000
0.300
0.390
0.400
0.400000000
0.407
0.500
0.500000000
0.590
0.600
0.600000000
0.7
0.700
0.700000000
0.740
0.800000000
0.815
0.860
0.890
0.9
0.900
0.900000000
0.920
0.950
0.970000000
0E-9
1.0
1.000
1.000000000
1.019
1.020000000
1.04
1.040000000
1.070000000
1.09
1.090
1.090000000
1.100
1.100000000
1.18
1.180
1.180000000
1.190000000
1.200
1.200000000
1.210
1.220000000
1.222
1.260
1.260000000
1.28
1.280
1.280000000
1.3
1.300
1.300000000
1.320000000
1.330000000
1.340000000
1.358000000
1.38
1.380
1.390000000
1.400
1.400000000
1.410
1.430000000
1.480
1.480000000
1.481
1.5
1.500
1.500000000
1.510000000
1.550
1.580000000
1.600
1.600000000
1.630
1.630000000
1.640000000
1.660
1.68
1.680000000
1.700
1.700000000
1.730000000
1.746
1.75
1.750
1.780000000
1.800
1.800000000
1.810
1.830
1.833
1.870000000
1.880
1.900
1.900000000
1.92
1.920000000
1.970
1.970000000
1.980000000
1.990000000
10.000
10.000000000
10.010000000
10.100
10.185
10.200
10.200000000
10.300000000
10.310000000
10.400
10.400000000
10.500000000
10.600
10.700000000
10.800
10.800000000
10.900000000
10.968
10000.000000000
101.900000000
11.000
11.000000000
11.100000000
11.200000000
11.240000000
11.300
11.300000000
11.350000000
11.400000000
11.500000000
11.600000000
11.640
11.8
11.800
11.800000000
11.883
11.900000000
12.000
12.000000000
12.100000000
12.200
12.200000000
12.222
12.300000000
12.460000000
12.500000000
12.6
12.600000000
12.700000000
12.900000000
13.000
13.000000000
13.100000000
13.200000000
13.300
13.300000000
13.600000000
13.620
13.700
13.800
13.800000000
13.900
130.000000000
14.000
14.000000000
14.050000000
14.100000000
14.400
14.500000000
14.580000000
14.600
14.600000000
14.800
14.800000000
14.900000000
149.500000000
15.000
15.000000000
15.100000000
15.400000000
15.600000000
15.700000000
15.900000000
155.400000000
16.000
16.000000000
16.300000000
16.400000000
16.500
16.600000000
16.700000000
16.800000000
17.000
17.000000000
17.120000000
17.200000000
17.300000000
17.360000000
17.500000000
17.800000000
18.000000000
18.200000000
18.300000000
18.400000000
18.430000000
18.500000000
18.650000000
18.700
185.000
19.000
19.000000000
19.100000000
19.200
19.200000000
19.280000000
19.400000000
19.600000000
19.700000000
190.000000000
190.700
193.900000000
199.700000000
2.000
2.000000000
2.037
2.04
2.070000000
2.072
2.090000000
2.100
2.100000000
2.110000000
2.2
2.200
2.200000000
2.220000000
2.241
2.246
2.3
2.300
2.300000000
2.320000000
2.370
2.370000000
2.380
2.400
2.400000000
2.444
2.500
2.500000000
2.540
2.570000000
2.6
2.600
2.600000000
2.660000000
2.670000000
2.680
2.680000000
2.70
2.700
2.700000000
2.730000000
2.780
2.8
2.800
2.800000000
2.840
2.860000000
2.900
2.900000000
2.910
2.960
2.960000000
20.000000000
20.200
20.300000000
20.400000000
20.470000000
20.7
20.700
20.700000000
20.900000000
202.800000000
205.300000000
21.000000000
21.100000000
21.700000000
21.791
210.800000000
213.100000000
22.000
22.000000000
22.100000000
22.200000000
22.900000000
23.000
23.000000000
23.490000000
23.500
23.700000000
23.730000000
24.000
24.000000000
24.400000000
24.500000000
24.7
25.000
25.000000000
25.200000000
25.500000000
25.800000000
26.000
26.000000000
26.100000000
26.400
26.600000000
266.400000000
27.000000000
27.200
27.200000000
27.400000000
28.000
28.000000000
28.300000000
28.600
28.990000000
29.000
29.000000000
29.600000000
29.800000000
29.900000000
3.000
3.000000000
3.030
3.056
3.08
3.080000000
3.100
3.100000000
3.134
3.140000000
3.16
3.160000000
3.178
3.200
3.200000000
3.210
3.210000000
3.240
3.240000000
3.259
3.260000000
3.300
3.300000000
3.310
3.340000000
3.400
3.400000000
3.42
3.450
3.460000000
3.467
3.500
3.500000000
3.55
3.550
3.560000000
3.600
3.600000000
3.65
3.650000000
3.700
3.700000000
3.750
3.750000000
3.800
3.800000000
3.900
3.900000000
30.000000000
30.600000000
31.000
31.000000000
31.600000000
31.700
32.000000000
32.300000000
32.600000000
32.700000000
32.900000000
33.000000000
33.100000000
33.800000000
33.900000000
34.000000000
34.700000000
34.900000000
35.000000000
35.090000000
35.400000000
35.500000000
35.600000000
36.000000000
36.700000000
360.000000000
37.000
37.000000000
37.100000000
37.200000000
37.900
370.000000000
38.000
38.000000000
38.500000000
38.600000000
38.700000000
380.000000000
388.000000000
4.000
4.000000000
4.012
4.030
4.070
4.074
4.074000000
4.100
4.100000000
4.140000000
4.190
4.200
4.200000000
4.240000000
4.300
4.300000000
4.4
4.400
4.400000000
4.440
4.440000000
4.450000000
4.500
4.500000000
4.600
4.600000000
4.630
4.700
4.700000000
4.701
4.727
4.740
4.740000000
4.753
4.780000000
4.793
4.800
4.800000000
4.830000000
4.838
4.900
4.900000000
4.930
40.000000000
40.300000000
40.450000000
41.400000000
42.400000000
42.500000000
42.700000000
420.000000000
44.400000000
44.500000000
44.600000000
45.000000000
47.000000000
470.000000000
48.000000000
48.800000000
5.000
5.000000000
5.030
5.050
5.093
5.100
5.100000000
5.130000000
5.200
5.200000000
5.230
5.300
5.300000000
5.330
5.340000000
5.390
5.400
5.400000000
5.432
5.500
5.500000000
5.520000000
5.600
5.600000000
5.620000000
5.700
5.700000000
5.710
5.720
5.800
5.800000000
5.900
5.900000000
5.920
50.000000000
51.500000000
54.300000000
54.800000000
55.000
55.500
55.900000000
56.450000000
57.000000000
58.000
58.000000000
59.200000000
6.000000000
6.020000000
6.100
6.100000000
6.111
6.139
6.173
6.200
6.200000000
6.300
6.300000000
6.366
6.400
6.400000000
6.410000000
6.500
6.500000000
6.510000000
6.518
6.600
6.600000000
6.700
6.700000000
6.710
6.790
6.800
6.800000000
6.810
6.820000000
6.900
6.900000000
6.926
60.000000000
60.700000000
61.000000000
62.400000000
63.000000000
64.000000000
64.200000000
65.300000000
69.100000000
7.000
7.000000000
7.020000000
7.100
7.100000000
7.200
7.200000000
7.280
7.300
7.300000000
7.320000000
7.333
7.4
7.400
7.400000000
7.480000000
7.500
7.500000000
7.550000000
7.580000000
7.600
7.600000000
7.7
7.700000000
7.800000000
7.890000000
7.900
7.900000000
7.920000000
71.000000000
71.700000000
72.000000000
74.000000000
75.500
79.600000000
790.000000000
8.000
8.000000000
8.010000000
8.030000000
8.100
8.100000000
8.148
8.200
8.200000000
8.29
8.290000000
8.300000000
8.400
8.400000000
8.470
8.488
8.500
8.500000000
8.600
8.600000000
8.700
8.700000000
8.800
8.800000000
8.880000000
8.900
8.900000000
8.960
8.963
84.000
84.400000000
9.000
9.000000000
9.08
9.100
9.100000000
9.200000000
9.300000000
9.370000000
9.400
9.400000000
9.470
9.470000000
9.500
9.500000000
9.540
9.600
9.600000000
9.620000000
9.670
9.670000000
9.700000000
9.778
9.800000000
9.870
9.870000000
9.900
9.900000000
9.970000000
90.300000000
93.500000000
94.700000000
97.700000000
99.200000000
<0.1
<0.5
<1
<1.0
<1.00
<LC
<LD
LD<X<LC
LD<x<LC
nan

In [14]:
oan

,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,geometry,fuente
0,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29873.0,RÍO NEGRO,2019-09-05 16:00:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
1,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29985.0,RÍO NEGRO,2019-10-31 09:40:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
2,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31062.0,RÍO NEGRO,2020-06-04 14:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,POINT (-57.41304 -32.9058),OAN
3,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31410.0,RÍO NEGRO,2020-08-06 12:46:00,CloA_(lab),µg/L,33.000000000,0.700000000,2.2,33.000000000,POINT (-57.41304 -32.9058),OAN
4,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31851.0,RÍO NEGRO,2020-11-19 12:29:00,CloA_(lab),µg/L,2.600000000,0.700000000,2.2,2.600000000,POINT (-57.41304 -32.9058),OAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5181,Playa,01SI,100803,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.52111 -32.81884),OAN
5182,Playa,01CU,100804,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.52502 -32.81838),OAN
5183,Playa,01PN,100806,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.53247 -32.81044),OAN
5184,Playa,07PV,100709,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-58.1489 -32.6381),OAN
5185,Playa,01BI,100791,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-55.96207 -31.66785),OAN

In [9]:
iguales = gpd.sjoin_nearest(
    gems_utm, oan_utm,
    how='inner',
    max_distance=0.1,
    distance_col='dist'
)

In [10]:
gems_stations = gems_utm["geometry"].unique()
oan_stations = oan_utm["geometry"].unique()

In [11]:
gems_stations = gpd.GeoDataFrame(
    geometry=gems_utm["geometry"].unique(),
    crs=gems_utm.crs,
)
oan_stations = gpd.GeoDataFrame(
    geometry = oan_utm["geometry"].unique(),
    crs = oan_utm.crs
)

In [12]:
iguales = gpd.sjoin_nearest(
    gems_stations, oan_stations,
    how='inner',
    max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
    distance_col='dist'
)
iguales = iguales.drop(columns=["index_right", "dist"])

In [13]:
iguales.shape

(150, 1)

(150, 1)

Esto nos dice que tanto en los registros de OAN como en los de Gems, existen estaciones que son identicas.

Lo que no significa que sean las mismas mediciones ni los mismos dias, eso es algo que tenemos que comprobar todavia.

Pero puede ser que estos datos sean compartidos entre ambas organizaciones.

In [14]:
iguales.head(5)

                         geometry
0  POINT (649386.009 6180413.463)
1  POINT (664852.016 6189770.245)
2  POINT (570470.059 6220119.303)
3  POINT (581348.445 6603897.643)
4  POINT (560699.232 6625269.716)

                         geometry
0  POINT (649386.009 6180413.463)
1  POINT (664852.016 6189770.245)
2  POINT (570470.059 6220119.303)
3  POINT (581348.445 6603897.643)
4  POINT (560699.232 6625269.716)

In [15]:
#4326
#oan_coords = oan_utm.to_crs(4326)

In [16]:
iguales_wgs84 = iguales.to_crs(4326).round(4)

iguales_wgs84.head(5)

                      geometry
0    POINT (-55.3727 -34.5071)
1    POINT (-55.2061 -34.4204)
2   POINT (-56.2355 -34.15747)
3  POINT (-56.15059 -30.69494)
4  POINT (-56.36744 -30.50333)

                      geometry
0    POINT (-55.3727 -34.5071)
1    POINT (-55.2061 -34.4204)
2   POINT (-56.2355 -34.15747)
3  POINT (-56.15059 -30.69494)
4  POINT (-56.36744 -30.50333)

In [17]:
#p1 = iguales_wgs84.geometry.iloc[0]

In [18]:
#p1.x, p1.y

In [19]:
gems_utm.head()

,estacion,Decision,param,fecha,value,unit,depth,granularidad,geometry,fuente
0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0000,mg/l,0.3,DIA,POINT (649386.009 6180413.463),GEMS
1,URY00008,dudoso,Chl-a,2018-11-12 08:30:00,0.0000,mg/l,0.3,DIA,POINT (664852.016 6189770.245),GEMS
6,URY00029,si,Chl-a,2017-02-22 11:00:00,0.0004,mg/l,0.3,DIA,POINT (570470.059 6220119.303),GEMS
7,URY00029,si,Chl-a,2017-04-19 13:00:00,0.0007,mg/l,0.3,DIA,POINT (570470.059 6220119.303),GEMS
8,URY00029,si,Chl-a,2017-12-13 11:44:00,0.0286,mg/l,0.3,DIA,POINT (570470.059 6220119.303),GEMS

,estacion,Decision,param,fecha,value,unit,depth,granularidad,geometry,fuente
0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0000,mg/l,0.3,DIA,POINT (649386.009 6180413.463),GEMS
1,URY00008,dudoso,Chl-a,2018-11-12 08:30:00,0.0000,mg/l,0.3,DIA,POINT (664852.016 6189770.245),GEMS
6,URY00029,si,Chl-a,2017-02-22 11:00:00,0.0004,mg/l,0.3,DIA,POINT (570470.059 6220119.303),GEMS
7,URY00029,si,Chl-a,2017-04-19 13:00:00,0.0007,mg/l,0.3,DIA,POINT (570470.059 6220119.303),GEMS
8,URY00029,si,Chl-a,2017-12-13 11:44:00,0.0286,mg/l,0.3,DIA,POINT (570470.059 6220119.303),GEMS

In [20]:
p1 = iguales.iloc[[0]]
p1

                         geometry
0  POINT (649386.009 6180413.463)

                         geometry
0  POINT (649386.009 6180413.463)

In [21]:
chla_p1_gems = gpd.sjoin_nearest(
    p1, gems_utm,
    how='inner',
    max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
    distance_col='dist'
)

In [22]:
chla_p1_gems.head()

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0,mg/l,0.3,DIA,GEMS,0.0

In [23]:
OAN_p1_chla = gpd.sjoin_nearest(
    p1, oan_utm,
    how='inner',
    max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
    distance_col='dist'
)

In [24]:
OAN_p1_chla.head()

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
0,POINT (649386.009 6180413.463),5149,Playa,08AB,100012,1.0,LAVALLEJA,2018-11-12 23:20:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
0,POINT (649386.009 6180413.463),5149,Playa,08AB,100012,1.0,LAVALLEJA,2018-11-12 23:20:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

In [25]:
def examinar_punto(p):
    chla_p_gems = gpd.sjoin_nearest(
        p, gems_utm,
        how='inner',
        max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
        distance_col='dist'
    ) 

    OAN_p_chla = gpd.sjoin_nearest(
        p, oan_utm,
        how='inner',
        max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
        distance_col='dist'
    )
    
    display(chla_p_gems)
    display(OAN_p_chla)

In [26]:
examinar_punto(p1)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
0,POINT (649386.009 6180413.463),5149,Playa,08AB,100012,1.0,LAVALLEJA,2018-11-12 23:20:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
0,POINT (649386.009 6180413.463),5149,Playa,08AB,100012,1.0,LAVALLEJA,2018-11-12 23:20:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

In [27]:
p2 = iguales.iloc[[1]]
examinar_punto(p2)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
1,POINT (664852.016 6189770.245),1,URY00008,dudoso,Chl-a,2018-11-12 08:30:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
1,POINT (664852.016 6189770.245),5121,Playa,06SF,100014,0.0,LAVALLEJA,2018-11-12 08:30:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
1,POINT (664852.016 6189770.245),1,URY00008,dudoso,Chl-a,2018-11-12 08:30:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
1,POINT (664852.016 6189770.245),5121,Playa,06SF,100014,0.0,LAVALLEJA,2018-11-12 08:30:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

In [28]:
p3 = iguales.iloc[[2]]
examinar_punto(p3)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
2,POINT (570470.059 6220119.303),6,URY00029,si,Chl-a,2017-02-22 11:00:00,0.0004,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),7,URY00029,si,Chl-a,2017-04-19 13:00:00,0.0007,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),8,URY00029,si,Chl-a,2017-12-13 11:44:00,0.0286,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),9,URY00029,si,Chl-a,2018-02-21 11:15:00,0.0049,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),10,URY00029,si,Chl-a,2018-10-17 11:43:00,0.0025,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),11,URY00029,si,Chl-a,2019-04-24 11:00:00,0.0023,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),20,URY00029,si,Chl-a,2022-10-19 11:26:00,0.0071,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),19,URY00029,si,Chl-a,2022-08-31 11:09:00,0.0096,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),18,URY00029,si,Chl-a,2022-02-22 13:37:00,0.0067,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),17,URY00029,si,Chl-a,2021-12-15 11:00:00,0.0740,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),16,URY00029,si,Chl-a,2020-12-09 10:50:00,0.0070,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),15,URY00029,si,Chl-a,2020-10-14 11:27:00,0.0033,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),14,URY00029,si,Chl-a,2020-08-12 11:42:00,0.0028,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),21,URY00029,si,Chl-a,2022-12-21 10:46:00,0.0180,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),13,URY00029,si,Chl-a,2020-02-18 11:10:00,0.0062,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),12,URY00029,si,Chl-a,2019-12-11 10:50:00,0.0840,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
2,POINT (570470.059 6220119.303),1734,Agua rio Santa Lucia DCA,XSLH030.S,100201,26596.0,FLORIDA,2017-10-18 11:58:00,CloA_(lab),µg/L,<LC,0.600,1.5,<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1733,Agua rio Santa Lucia DCA,XSLH030.S,100201,26124.0,FLORIDA,2017-06-21 11:05:00,CloA_(lab),µg/L,<LD,0.600,1.5,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1745,Agua rio Santa Lucia DCA,XSLH030.S,100201,29435.0,FLORIDA,2019-06-12 11:15:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1771,Agua rio Santa Lucia DCA,XSLH030.S,100201,37542.0,FLORIDA,2024-06-04 12:19:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1772,Agua rio Santa Lucia DCA,XSLH030.S,100201,37767.0,FLORIDA,2024-08-13 10:41:00,CloA_(lab),µg/L,3.500000000,0.700000000,2.2,3.500000000,OAN,0.0
2,POINT (570470.059 6220119.303),1773,Agua rio Santa Lucia DCA,XSLH030.S,100201,38119.0,FLORIDA,2024-10-22 12:00:00,CloA_(lab),µg/L,11.000000000,0.700000000,2.2,11.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1774,Agua rio Santa Lucia DCA,XSLH030.S,100201,38432.0,FLORIDA,2024-12-10 11:49:00,CloA_(lab),µg/L,2.400000000,0.700000000,2.2,2.400000000,OAN,0.0
2,POINT (570470.059 6220119.303),1769,Agua rio Santa Lucia DCA,XSLH030.S,100201,36953.0,FLORIDA,2024-02-06 11:56:00,CloA_(lab),µg/L,7.900000000,0.700000000,2.2,7.900000000,OAN,0.0
2,POINT (570470.059 6220119.303),1753,Agua rio Santa Lucia DCA,XSLH030.S,100201,31429.0,FLORIDA,2020-08-12 11:42:00,CloA_(lab),µg/L,2.800000000,0.700000000,2.2,2.800000000,OAN,0.0
2,POINT (570470.059 6220119.303),1767,Agua rio Santa Lucia DCA,XSLH030.S,100201,36744.0,FLORIDA,2023-12-13 09:20:00,CloA_(lab),µg/L,2.200000000,0.700000000,2.2,2.200000000,OAN,0.0
2,POINT (570470.059 6220119.303),1735,Agua rio Santa Lucia DCA,XSLH030.S,100201,26859.0,FLORIDA,2017-12-13 11:44:00,CloA_(lab),µg/L,28.600,0.100,0.1,28.600,OAN,0.0
2,POINT (570470.059 6220119.303),1743,Agua rio Santa Lucia DCA,XSLH030.S,100201,27919.0,FLORIDA,2018-08-15 11:59:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1742,Agua rio Santa Lucia DCA,XSLH030.S,100201,28894.0,FLORIDA,2019-02-20 12:10:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1741,Agua rio Santa Lucia DCA,XSLH030.S,100201,28606.0,FLORIDA,2018-12-12 11:24:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1740,Agua rio Santa Lucia DCA,XSLH030.S,100201,28336.0,FLORIDA,2018-10-17 11:43:00,CloA_(lab),µg/L,2.500,0.700,2.2,2.500,OAN,0.0
2,POINT (570470.059 6220119.303),1739,Agua rio Santa Lucia DCA,XSLH030.S,100201,27211.0,FLORIDA,2018-02-21 11:15:00,CloA_(lab),µg/L,4.900,0.700,2.2,4.900,OAN,0.0
2,POINT (570470.059 6220119.303),1738,Agua rio Santa Lucia DCA,XSLH030.S,100201,27710.0,FLORIDA,2018-06-13 11:20:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1737,Agua rio Santa Lucia DCA,XSLH030.S,100201,25907.0,FLORIDA,2017-04-19 13:00:00,CloA_(lab),µg/L,0.700,NaN,0.1,0.700,OAN,0.0
2,POINT (570470.059 6220119.303),1736,Agua rio Santa Lucia DCA,XSLH030.S,100201,25650.0,FLORIDA,2017-02-22 11:00:00,CloA_(lab),µg/L,0.400,NaN,0.1,0.400,OAN,0.0
2,POINT (570470.059 6220119.303),1744,Agua rio Santa Lucia DCA,XSLH030.S,100201,29219.0,FLORIDA,2019-04-24 11:00:00,CloA_(lab),µg/L,2.300,0.700,2.2,2.300,OAN,0.0
2,POINT (570470.059 6220119.303),1747,Agua rio Santa Lucia DCA,XSLH030.S,100201,30029.0,FLORIDA,2019-10-23 11:30:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1746,Agua rio Santa Lucia DCA,XSLH030.S,100201,29730.0,FLORIDA,2019-08-14 11:20:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1759,Agua rio Santa Lucia DCA,XSLH030.S,100201,33276.0,FLORIDA,2021-12-15 11:00:00,CloA_(lab),µg/L,74.000000000,0.700000000,2.2,74.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1766,Agua rio Santa Lucia DCA,XSLH030.S,100201,35563.0,FLORIDA,2023-02-14 11:03:00,CloA_(lab),µg/L,22.000000000,0.700000000,2.2,22.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1768,Agua rio Santa Lucia DCA,XSLH030.S,100201,36535.0,FLORIDA,2023-10-18 11:55:00,CloA_(lab),µg/L,9.100000000,0.700000000,2.2,9.100000000,OAN,0.0
2,POINT (570470.059 6220119.303),1760,Agua rio Santa Lucia DCA,XSLH030.S,100201,33622.0,FLORIDA,2022-02-22 13:37:00,CloA_(lab),µg/L,6.700000000,0.700000000,2.2,6.700000000,OAN,0.0
2,POINT (570470.059 6220119.303),1758,Agua rio Santa Lucia DCA,XSLH030.S,100201,32954.0,FLORIDA,2021-10-13 10:38:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1761,Agua rio Santa Lucia DCA,XSLH030.S,100201,33871.0,FLORIDA,2022-04-20 11:10:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1762,Agua rio Santa Lucia DCA,XSLH030.S,100201,34685.0,FLORIDA,2022-08-31 11:09:00,CloA_(lab),µg/L,9.600000000,0.700000000,2.2,9.600000000,OAN,0.0
2,POINT (570470.059 6220119.303),1763,Agua rio Santa Lucia DCA,XSLH030.S,100201,34914.0,FLORIDA,2022-10-19 11:26:00,CloA_(lab),µg/L,7.100000000,0.700000000,2.2,7.100000000,OAN,0.0
2,POINT (570470.059 6220119.303),1764,Agua rio Santa Lucia DCA,XSLH030.S,100201,35412.0,FLORIDA,2022-12-21 10:46:00,CloA_(lab),µg/L,18.000000000,0.700000000,2.2,18.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1765,Agua rio Santa Lucia DCA,XSLH030.S,100201,36337.0,FLORIDA,2023-08-30 00:00:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1757,Agua rio Santa Lucia DCA,XSLH030.S,100201,32451.0,FLORIDA,2021-07-28 10:52:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1756,Agua rio Santa Lucia DCA,XSLH030.S,100201,32744.0,FLORIDA,2021-09-01 11:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1755,Agua rio Santa Lucia DCA,XSLH030.S,100201,32001.0,FLORIDA,2020-12-09 10:50:00,CloA_(lab),µg/L,7.000000000,0.700000000,2.2,7.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1754,Agua rio Santa Lucia DCA,XSLH030.S,100201,31660.0,FLORIDA,2020-10-14 11:27:00,CloA_(lab),µg/L,3.300000000,0.700000000,2.2,3.300000000,OAN,0.0
2,POINT (570470.059 6220119.303),1770,Agua rio Santa Lucia DCA,XSLH030.S,100201,37288.0,FLORIDA,2024-04-02 09:57:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1752,Agua rio Santa Lucia DCA,XSLH030.S,100201,31090.0,FLORIDA,2020-06-10 11:30:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1751,Agua rio Santa Lucia DCA,XSLH030.S,100201,26418.0,FLORIDA,2017-08-16 11:27:00,CloA_(lab),µg/L,<LD,0.600000000,1.5,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1750,Agua rio Santa Lucia DCA,XSLH030.S,100201,30985.0,FLORIDA,2020-04-28 11:25:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1749,Agua rio Santa Lucia DCA,XSLH030.S,100201,30590.0,FLORIDA,2020-02-18 11:10:00,CloA_(lab),µg/L,6.200000000,0.700000000,2.2,6.200000000,OAN,0.0
2,POINT (570470.059 6220119.303),1748,Agua rio Santa Lucia DCA,XSLH030.S,100201,30283.0,FLORIDA,2019-12-11 10:50:00,CloA_(lab),µg/L,84.000,0.700,2.2,84.000,OAN,0.0

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
2,POINT (570470.059 6220119.303),6,URY00029,si,Chl-a,2017-02-22 11:00:00,0.0004,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),7,URY00029,si,Chl-a,2017-04-19 13:00:00,0.0007,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),8,URY00029,si,Chl-a,2017-12-13 11:44:00,0.0286,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),9,URY00029,si,Chl-a,2018-02-21 11:15:00,0.0049,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),10,URY00029,si,Chl-a,2018-10-17 11:43:00,0.0025,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),11,URY00029,si,Chl-a,2019-04-24 11:00:00,0.0023,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),20,URY00029,si,Chl-a,2022-10-19 11:26:00,0.0071,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),19,URY00029,si,Chl-a,2022-08-31 11:09:00,0.0096,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),18,URY00029,si,Chl-a,2022-02-22 13:37:00,0.0067,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),17,URY00029,si,Chl-a,2021-12-15 11:00:00,0.0740,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),16,URY00029,si,Chl-a,2020-12-09 10:50:00,0.0070,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),15,URY00029,si,Chl-a,2020-10-14 11:27:00,0.0033,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),14,URY00029,si,Chl-a,2020-08-12 11:42:00,0.0028,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),21,URY00029,si,Chl-a,2022-12-21 10:46:00,0.0180,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),13,URY00029,si,Chl-a,2020-02-18 11:10:00,0.0062,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),12,URY00029,si,Chl-a,2019-12-11 10:50:00,0.0840,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
2,POINT (570470.059 6220119.303),1734,Agua rio Santa Lucia DCA,XSLH030.S,100201,26596.0,FLORIDA,2017-10-18 11:58:00,CloA_(lab),µg/L,<LC,0.600,1.5,<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1733,Agua rio Santa Lucia DCA,XSLH030.S,100201,26124.0,FLORIDA,2017-06-21 11:05:00,CloA_(lab),µg/L,<LD,0.600,1.5,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1745,Agua rio Santa Lucia DCA,XSLH030.S,100201,29435.0,FLORIDA,2019-06-12 11:15:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1771,Agua rio Santa Lucia DCA,XSLH030.S,100201,37542.0,FLORIDA,2024-06-04 12:19:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1772,Agua rio Santa Lucia DCA,XSLH030.S,100201,37767.0,FLORIDA,2024-08-13 10:41:00,CloA_(lab),µg/L,3.500000000,0.700000000,2.2,3.500000000,OAN,0.0
2,POINT (570470.059 6220119.303),1773,Agua rio Santa Lucia DCA,XSLH030.S,100201,38119.0,FLORIDA,2024-10-22 12:00:00,CloA_(lab),µg/L,11.000000000,0.700000000,2.2,11.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1774,Agua rio Santa Lucia DCA,XSLH030.S,100201,38432.0,FLORIDA,2024-12-10 11:49:00,CloA_(lab),µg/L,2.400000000,0.700000000,2.2,2.400000000,OAN,0.0
2,POINT (570470.059 6220119.303),1769,Agua rio Santa Lucia DCA,XSLH030.S,100201,36953.0,FLORIDA,2024-02-06 11:56:00,CloA_(lab),µg/L,7.900000000,0.700000000,2.2,7.900000000,OAN,0.0
2,POINT (570470.059 6220119.303),1753,Agua rio Santa Lucia DCA,XSLH030.S,100201,31429.0,FLORIDA,2020-08-12 11:42:00,CloA_(lab),µg/L,2.800000000,0.700000000,2.2,2.800000000,OAN,0.0
2,POINT (570470.059 6220119.303),1767,Agua rio Santa Lucia DCA,XSLH030.S,100201,36744.0,FLORIDA,2023-12-13 09:20:00,CloA_(lab),µg/L,2.200000000,0.700000000,2.2,2.200000000,OAN,0.0
2,POINT (570470.059 6220119.303),1735,Agua rio Santa Lucia DCA,XSLH030.S,100201,26859.0,FLORIDA,2017-12-13 11:44:00,CloA_(lab),µg/L,28.600,0.100,0.1,28.600,OAN,0.0
2,POINT (570470.059 6220119.303),1743,Agua rio Santa Lucia DCA,XSLH030.S,100201,27919.0,FLORIDA,2018-08-15 11:59:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1742,Agua rio Santa Lucia DCA,XSLH030.S,100201,28894.0,FLORIDA,2019-02-20 12:10:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1741,Agua rio Santa Lucia DCA,XSLH030.S,100201,28606.0,FLORIDA,2018-12-12 11:24:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1740,Agua rio Santa Lucia DCA,XSLH030.S,100201,28336.0,FLORIDA,2018-10-17 11:43:00,CloA_(lab),µg/L,2.500,0.700,2.2,2.500,OAN,0.0
2,POINT (570470.059 6220119.303),1739,Agua rio Santa Lucia DCA,XSLH030.S,100201,27211.0,FLORIDA,2018-02-21 11:15:00,CloA_(lab),µg/L,4.900,0.700,2.2,4.900,OAN,0.0
2,POINT (570470.059 6220119.303),1738,Agua rio Santa Lucia DCA,XSLH030.S,100201,27710.0,FLORIDA,2018-06-13 11:20:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1737,Agua rio Santa Lucia DCA,XSLH030.S,100201,25907.0,FLORIDA,2017-04-19 13:00:00,CloA_(lab),µg/L,0.700,NaN,0.1,0.700,OAN,0.0
2,POINT (570470.059 6220119.303),1736,Agua rio Santa Lucia DCA,XSLH030.S,100201,25650.0,FLORIDA,2017-02-22 11:00:00,CloA_(lab),µg/L,0.400,NaN,0.1,0.400,OAN,0.0
2,POINT (570470.059 6220119.303),1744,Agua rio Santa Lucia DCA,XSLH030.S,100201,29219.0,FLORIDA,2019-04-24 11:00:00,CloA_(lab),µg/L,2.300,0.700,2.2,2.300,OAN,0.0
2,POINT (570470.059 6220119.303),1747,Agua rio Santa Lucia DCA,XSLH030.S,100201,30029.0,FLORIDA,2019-10-23 11:30:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1746,Agua rio Santa Lucia DCA,XSLH030.S,100201,29730.0,FLORIDA,2019-08-14 11:20:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1759,Agua rio Santa Lucia DCA,XSLH030.S,100201,33276.0,FLORIDA,2021-12-15 11:00:00,CloA_(lab),µg/L,74.000000000,0.700000000,2.2,74.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1766,Agua rio Santa Lucia DCA,XSLH030.S,100201,35563.0,FLORIDA,2023-02-14 11:03:00,CloA_(lab),µg/L,22.000000000,0.700000000,2.2,22.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1768,Agua rio Santa Lucia DCA,XSLH030.S,100201,36535.0,FLORIDA,2023-10-18 11:55:00,CloA_(lab),µg/L,9.100000000,0.700000000,2.2,9.100000000,OAN,0.0
2,POINT (570470.059 6220119.303),1760,Agua rio Santa Lucia DCA,XSLH030.S,100201,33622.0,FLORIDA,2022-02-22 13:37:00,CloA_(lab),µg/L,6.700000000,0.700000000,2.2,6.700000000,OAN,0.0
2,POINT (570470.059 6220119.303),1758,Agua rio Santa Lucia DCA,XSLH030.S,100201,32954.0,FLORIDA,2021-10-13 10:38:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1761,Agua rio Santa Lucia DCA,XSLH030.S,100201,33871.0,FLORIDA,2022-04-20 11:10:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1762,Agua rio Santa Lucia DCA,XSLH030.S,100201,34685.0,FLORIDA,2022-08-31 11:09:00,CloA_(lab),µg/L,9.600000000,0.700000000,2.2,9.600000000,OAN,0.0
2,POINT (570470.059 6220119.303),1763,Agua rio Santa Lucia DCA,XSLH030.S,100201,34914.0,FLORIDA,2022-10-19 11:26:00,CloA_(lab),µg/L,7.100000000,0.700000000,2.2,7.100000000,OAN,0.0
2,POINT (570470.059 6220119.303),1764,Agua rio Santa Lucia DCA,XSLH030.S,100201,35412.0,FLORIDA,2022-12-21 10:46:00,CloA_(lab),µg/L,18.000000000,0.700000000,2.2,18.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1765,Agua rio Santa Lucia DCA,XSLH030.S,100201,36337.0,FLORIDA,2023-08-30 00:00:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1757,Agua rio Santa Lucia DCA,XSLH030.S,100201,32451.0,FLORIDA,2021-07-28 10:52:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1756,Agua rio Santa Lucia DCA,XSLH030.S,100201,32744.0,FLORIDA,2021-09-01 11:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1755,Agua rio Santa Lucia DCA,XSLH030.S,100201,32001.0,FLORIDA,2020-12-09 10:50:00,CloA_(lab),µg/L,7.000000000,0.700000000,2.2,7.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1754,Agua rio Santa Lucia DCA,XSLH030.S,100201,31660.0,FLORIDA,2020-10-14 11:27:00,CloA_(lab),µg/L,3.300000000,0.700000000,2.2,3.300000000,OAN,0.0
2,POINT (570470.059 6220119.303),1770,Agua rio Santa Lucia DCA,XSLH030.S,100201,37288.0,FLORIDA,2024-04-02 09:57:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1752,Agua rio Santa Lucia DCA,XSLH030.S,100201,31090.0,FLORIDA,2020-06-10 11:30:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1751,Agua rio Santa Lucia DCA,XSLH030.S,100201,26418.0,FLORIDA,2017-08-16 11:27:00,CloA_(lab),µg/L,<LD,0.600000000,1.5,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1750,Agua rio Santa Lucia DCA,XSLH030.S,100201,30985.0,FLORIDA,2020-04-28 11:25:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1749,Agua rio Santa Lucia DCA,XSLH030.S,100201,30590.0,FLORIDA,2020-02-18 11:10:00,CloA_(lab),µg/L,6.200000000,0.700000000,2.2,6.200000000,OAN,0.0
2,POINT (570470.059 6220119.303),1748,Agua rio Santa Lucia DCA,XSLH030.S,100201,30283.0,FLORIDA,2019-12-11 10:50:00,CloA_(lab),µg/L,84.000,0.700,2.2,84.000,OAN,0.0

#### Que queremos?
0. 'iguales' es una lista de puntos que aparecen repetidos tanto en la fuente OAN como Gems (datos compartidos entre ambas organizaciones?)
1. Para cualquier punto p de 'iguales' lo que queremos es:
2. obtener los registros para ese mismo punto de oan y gems
3. concatenear esos registros para tener un unico dataframe
4. Eliminar duplicados: Es duplicado si 1) la medicion fue tomada en la misma fecha y el valor es el mismo (o la diferencia es despreciable)

In [35]:
iguales

                           geometry
0    POINT (649386.009 6180413.463)
1    POINT (664852.016 6189770.245)
2    POINT (570470.059 6220119.303)
3    POINT (581348.445 6603897.643)
4    POINT (560699.232 6625269.716)
..                              ...
147  POINT (518553.944 6362768.507)
148  POINT (518472.926 6362066.591)
149  POINT (697634.803 6136124.084)
150  POINT (716874.108 6144491.973)
151   POINT (600108.84 6489773.595)

[150 rows x 1 columns]

In [36]:
p = iguales.iloc[[32]]
p##?
#JOIN PUNTOS == OAN.PUNTOS == GEMS.PUNTOS 
#
#[p1, chla_oan, chla_gems]
#[p1, chla_oan, chla_gems]
#[p1, chla_oan, chla_gems]
#[p1, chla_oan, chla_gems]
#...
#[p2, chla_oan, chla_gems]
#[p2, chla_oan, chla_gems]
#[p2, chla_oan, chla_gems]
#[p2, chla_oan, chla_gems]
#...
#[pn, chla_oan, chla_gems]
#[pn, chla_oan, chla_gems]
#[pn, chla_oan, chla_gems]
#[pn, chla_oan, chla_gems]
#...
#

                          geometry
32  POINT (608644.563 6390123.956)

In [31]:
chla_p_gems = gpd.sjoin_nearest(
    p, gems_utm,
    how='inner',
    max_distance=0.1,
    distance_col='dist'
)

chla_p_oan = gpd.sjoin_nearest(
    p, oan_utm,
    how='inner',
    max_distance=0.1,
    distance_col='dist'
)

In [32]:
chla_p_gems.head(1)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
32,POINT (608644.563 6390123.956),556,URY00071,si,Chl-a,2022-11-15 13:50:00,0.0033,mg/l,0.3,DIA,GEMS,0.0

In [33]:
combinados = gpd.GeoDataFrame(
    pd.concat([chla_p_gems, chla_p_oan], ignore_index=True),
    geometry = "geometry",
    crs= oan_utm.crs
)

In [34]:
combinados

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
0,POINT (608644.563 6390123.956),556,URY00071,si,Chl-a,2022-11-15 13:50:00,0.0033,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,POINT (608644.563 6390123.956),553,URY00071,si,Chl-a,2021-03-09 13:07:00,0.0077,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,POINT (608644.563 6390123.956),545,URY00071,si,Chl-a,2018-01-16 13:28:00,0.0042,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,POINT (608644.563 6390123.956),546,URY00071,si,Chl-a,2018-04-10 14:20:00,0.0032,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,POINT (608644.563 6390123.956),547,URY00071,si,Chl-a,2018-09-25 13:30:00,0.0023,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,POINT (608644.563 6390123.956),548,URY00071,si,Chl-a,2019-01-16 11:30:00,0.0030,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,POINT (608644.563 6390123.956),549,URY00071,si,Chl-a,2019-03-19 14:20:00,0.0025,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,POINT (608644.563 6390123.956),550,URY00071,si,Chl-a,2019-10-08 12:53:00,0.0060,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,POINT (608644.563 6390123.956),551,URY00071,si,Chl-a,2020-01-28 14:12:00,0.0063,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,POINT (608644.563 6390123.956),552,URY00071,si,Chl-a,2020-09-29 14:35:00,0.0150,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,POINT (608644.563 6390123.956),554,URY00071,si,Chl-a,2021-11-30 13:00:00,0.0058,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,POINT (608644.563 6390123.956),555,URY00071,si,Chl-a,2022-01-18 14:19:00,0.0100,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,POINT (608644.563 6390123.956),1021,ERDB030.S,NaN,NaN,2021-11-30 13:00:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,33229.0,TACUAREMBÓ,CloA_(lab),µg/L,5.800000000,0.700000000,2.2,5.800000000
13,POINT (608644.563 6390123.956),1022,ERDB030.S,NaN,NaN,2022-01-18 14:19:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,33342.0,TACUAREMBÓ,CloA_(lab),µg/L,10.000000000,0.700000000,2.2,10.000000000
14,POINT (608644.563 6390123.956),1012,ERDB030.S,NaN,NaN,2019-03-19 14:20:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,29160.0,TACUAREMBÓ,CloA_(lab),µg/L,2.500,0.700,2.2,2.500
15,POINT (608644.563 6390123.956),1010,ERDB030.S,NaN,NaN,2018-09-25 13:30:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,28070.0,TACUAREMBÓ,CloA_(lab),µg/L,2.300,0.700,2.2,2.300
16,POINT (608644.563 6390123.956),1007,ERDB030.S,NaN,NaN,2017-10-03 13:08:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,26553.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC
17,POINT (608644.563 6390123.956),1023,ERDB030.S,NaN,NaN,2022-04-26 13:30:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,33926.0,TACUAREMBÓ,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD
18,POINT (608644.563 6390123.956),1024,ERDB030.S,NaN,NaN,2022-08-02 13:50:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,34334.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
19,POINT (608644.563 6390123.956),1008,ERDB030.S,NaN,NaN,2018-01-16 13:28:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,27010.0,TACUAREMBÓ,CloA_(lab),µg/L,4.200,0.700,2.2,4.200
20,POINT (608644.563 6390123.956),1005,ERDB030.S,NaN,NaN,2018-07-03 13:30:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,27867.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC
21,POINT (608644.563 6390123.956),1025,ERDB030.S,NaN,NaN,2022-11-15 13:50:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,35111.0,TACUAREMBÓ,CloA_(lab),µg/L,3.300000000,0.700000000,2.2,3.300000000
22,POINT (608644.563 6390123.956),1006,ERDB030.S,NaN,NaN,2017-07-04 09:03:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,26095.0,TACUAREMBÓ,CloA_(lab),µg/L,<LC,0.600,1.5,<LC
23,POINT (608644.563 6390123.956),1020,ERDB030.S,NaN,NaN,2021-09-07 13:22:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,32827.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
24,POINT (608644.563 6390123.956),1019,ERDB030.S,NaN,NaN,2021-03-09 13:07:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,32306.0,TACUAREMBÓ,CloA_(lab),µg/L,7.700000000,0.700000000,2.2,7.700000000
25,POINT (608644.563 6390123.956),1018,ERDB030.S,NaN,NaN,2020-06-23 14:59:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,31158.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
26,POINT (608644.563 6390123.956),1017,ERDB030.S,NaN,NaN,2020-09-29 14:35:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,31601.0,TACUAREMBÓ,CloA_(lab),µg/L,15.000000000,0.700000000,2.2,15.000000000
27,POINT (608644.563 6390123.956),1016,ERDB030.S,NaN,NaN,2020-05-05 13:21:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,30834.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
28,POINT (608644.563 6390123.956),1015,ERDB030.S,NaN,NaN,2020-01-28 14:12:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,30557.0,TACUAREMBÓ,CloA_(lab),µg/L,6.300000000,0.700000000,2.2,6.300000000
29,POINT (608644.563 6390123.956),1014,ERDB030.S,NaN,NaN,2019-10-08 12:53:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,30001.0,TACUAREMBÓ,CloA_(lab),µg/L,6.000000000,0.700000000,2.2,6.000000000
30,POINT (608644.563 6390123.956),1013,ERDB030.S,NaN,NaN,2019-06-26 10:28:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,29581.0,TACUAREMBÓ,CloA_(lab),µg/L,<LD,0.700,2.2,<LD
31,POINT (608644.563 6390123.956),1011,ERDB030.S,NaN,NaN,2019-01-16 11:30:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,28821.0,TACUAREMBÓ,CloA_(lab),µg/L,3.000,0.700,2.2,3.000
32,POINT (608644.563 6390123.956),1027,ERDB030.S,NaN,NaN,2023-08-08 13:21:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,36259.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
33,POINT (608644.563 6390123.956),1028,ERDB030.S,NaN,NaN,2023-11-07 15:42:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,36615.0,TACUAREMBÓ,CloA_(lab),µg/L,6.200000000,0.700000000,2.2,6.200000000
34,POINT (608644.563 6390123.956),1029,ERDB030.S,NaN,NaN,2024-01-16 12:31:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,36881.0,TACUAREMBÓ,CloA_(lab),µg/L,15.000000000,0.700000000,2.2,15.000000000
35,POINT (608644.563 6390123.956),1026,ERDB030.S,NaN,NaN,2023-01-24 13:45:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,35475.0,TACUAREMBÓ,CloA_(lab),µg/L,790.000000000,0.700000000,2.2,790.000000000
36,POINT (608644.563 6390123.956),1009,ERDB030.S,NaN,NaN,2018-04-10 14:20:00,NaN,NaN,NaN,NaN,...,Agua rio Negro DCA,100256.0,27421.0,TACUAREMBÓ,CloA_(lab),µg/L,3.200,0.700,2.2,3.200

In [35]:
combinados = combinados.set_index("fecha").sort_index()

In [51]:
N = combinados.shape[0]
EPS = 1e-5

fechas = []
value_chlas = []
geometries = []
fuentes = []
estaciones  = []

#mediciones_p_sinrep = gpd.GeoDataFrame(columns=["fecha", "value_chla", "geometry", "fuente", "estacion"], geometry = "geometry", crs = 32721)

def extract_chla_fila(fila):
    if fila["fuente"] == "OAN":
        #TODO: QUE hacer con LD y LC, otros valores
        chla = float(fila["valor_transformado"])
    elif fila["fuente"] == "GEMS":
        chla = float(fila["value"]) * 1000
    return chla, fila["fuente"]
    
for i in range(N - 1):
    fecha1 = combinados.index[i]
    fecha2 = combinados.index[i+1]
    if fecha1 == fecha2:
        fila1 = combinados.iloc[i]
        fila2 = combinados.iloc[i+1]
        chla_fila1, fuente1 = extract_chla_fila(fila1)
        chla_fila2, fuente2 = extract_chla_fila(fila2)
        if abs(chla_fila1 - chla_fila2) <= EPS:
            fechas.append(fecha1)
            value_chlas.append(chla_fila1)
            fuentes.append(fuente1)
            geometries.append(p)
            estaciones.append(fila1["estacion"])
    else:
        #append(f1)
        #append(f2)

4.1999998502433 4.2
3.2 3.1999999191612
2.3000000510364 2.3
3.000000026077 3.0
2.5 2.4999999441206
6.000000052154 6.0
6.3000000081956 6.3
14.9999996647238 15.0
7.6999999582767 7.7
5.7999999262392 5.8
9.9999997764825 10.0
3.3 3.2999999821186

                          geometry
32  POINT (608644.563 6390123.956)

In [37]:
chla_gems_iguales = gpd.sjoin_nearest(
    iguales, gems_utm,
    how='inner',
    max_distance=0.1,      
    distance_col='dist'
)

chla_oan_iguales = gpd.sjoin_nearest(
    iguales, oan_utm,
    how='inner',
    max_distance=0.1,      
    distance_col='dist'
)

In [38]:
chla_gems_iguales.shape

(3072, 12)

In [39]:
chla_oan_iguales.shape

(4251, 16)

In [40]:
combinados = gpd.GeoDataFrame(
    pd.concat([chla_gems_iguales, chla_oan_iguales], ignore_index=True),
    crs=oan_utm.crs,
    geometry ="geometry",
)

In [41]:
combinados.shape

(7323, 22)

In [42]:
combinados.head(3)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0000,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,POINT (664852.016 6189770.245),1,URY00008,dudoso,Chl-a,2018-11-12 08:30:00,0.0000,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,POINT (570470.059 6220119.303),6,URY00029,si,Chl-a,2017-02-22 11:00:00,0.0004,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
len(combinados["geometry"].unique()) == len(iguales)

True

In [44]:
#MISMO PUNTO, MISMA FECHA

In [45]:
combinados.iloc[[10]]

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
10,POINT (570470.059 6220119.303),18,URY00029,si,Chl-a,2022-02-22 13:37:00,0.0067,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Que queremos filtrar ahora?
En el paso anterior lo que hicimos fue filtrar todos los puntos que aparecen en ambas fuentes: OAN y Gems

1. Para cada punto queremos saber que mediciones estan repetidas
2. Una medicion puede estar repitidia si: Fue tomadad en la misma fecha y si el valor es el mismo

In [46]:
(combinados["fecha"].value_counts() >= 2).sum()

np.int64(1680)

In [81]:
p = iguales.iloc[20]
assert combinados.crs == iguales.crs, "Tienen que estar en el mismo Coordinate Reference System para poder comparar"

mediciones_de_p = combinados[combinados.geom_equals(p.geometry)]
mediciones_de_p

# A, B 

#misma_date = mediciones_de_p[mediciones_de_p["fecha"].isin(mediciones_de_p["fecha_hora"])]
#misma_date[["fecha", "fecha_hora"]]

#misma_date = mediciones_de_p[mediciones_de_p["fecha"] == mediciones_de_p["fecha_hora"]]


#fechas_gems = mediciones_de_p[~mediciones_de_p["fecha"].isna()]["fecha"]
#fechas_oan = mediciones_de_p[~mediciones_de_p["fecha_hora"].isna()]["fecha_hora"]

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
955,POINT (671890.038 6142737.153),1568,URY00080,si,Chl-a,2023-02-15 11:09:00,0.0032,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,POINT (671890.038 6142737.153),1558,URY00080,si,Chl-a,2022-11-16 12:38:00,0.0013,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957,POINT (671890.038 6142737.153),1559,URY00080,si,Chl-a,2022-11-22 11:52:00,0.0029,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,POINT (671890.038 6142737.153),1560,URY00080,si,Chl-a,2022-12-05 11:04:00,0.0012,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
959,POINT (671890.038 6142737.153),1561,URY00080,si,Chl-a,2022-12-30 12:20:00,0.0043,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,POINT (671890.038 6142737.153),1514,URY00080,si,Chl-a,2021-01-13 11:34:00,0.0047,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1097,POINT (671890.038 6142737.153),1513,URY00080,si,Chl-a,2021-01-08 10:53:00,0.0072,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1098,POINT (671890.038 6142737.153),1512,URY00080,si,Chl-a,2020-12-29 11:41:00,0.0044,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1099,POINT (671890.038 6142737.153),1524,URY00080,si,Chl-a,2021-03-31 11:40:00,0.0067,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4472,POINT (671890.038 6142737.153),4445,P4,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,Laguna del Sauce,100274.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
#mediciones_de_p

In [83]:
#idx_gems = fechas_gems[fechas_gems.isin(fechas_oan)].index
#idx_oan = fechas_oan[fechas_oan.isin(fechas_gems)].index

In [84]:
#mediciones_de_p.loc[idx_oan.union(idx_gems)] # [1, 2, 3] UNION [1, 4, 5] = [1, 2, 3, 4, 5]

In [85]:
mediciones_de_p = mediciones_de_p.set_index("fecha").sort_index()

In [90]:
mediciones_de_p.shape

(146, 21)

In [91]:
N = mediciones_de_p.shape[0]
eps = 1e-5
#[[a, b], [c, d], e]
def fila_extraer_chla(fila):
    if fila["fuente"] == "GEMS":
        chla = float(fila["value"])
    elif fila["fuente"] == "OAN":
        chla = float(fila["valor_transformado"]) / 1000
    return chla
    
for i in range(N - 1):
    if mediciones_de_p.index[i] == mediciones_de_p.index[i+1]:# ?????????
        print("IGUALES!")
        fila1 = mediciones_de_p.iloc[i]
        fila2 = mediciones_de_p.iloc[i+1]
        
        chla_f1 = fila_extraer_chla(fila1)
        chla_f2 = fila_extraer_chla(fila2)
        diff = abs(chla_f1 - chla_f2)
        if diff <= eps:
            # GUARDAR UNO SOLO!
            print(chla_f1, chla_f2, "Igual valor")
        else:
            print(chla_f1, chla_f2, "Diferente valor")
        #display()
        #display()
    else:
        print("fechas differentes!")
        
#N = len(mediciones
#for i in range(N):

fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!
fechas differentes!

In [88]:
mediciones_de_p.iloc[0].index

Index(['geometry', 'index_right', 'estacion', 'Decision', 'param', 'value',
       'unit', 'depth', 'granularidad', 'fuente', 'dist', 'nombre_programa',
       'id_estacion', 'nro_muestra', 'departamento', 'nombre_clave',
       'uni_nombre', 'valor_original', 'limite_deteccion',
       'limite_cuantificacion', 'valor_transformado'],
      dtype='str')

In [66]:
mediciones_de_p.iloc[[0]]

,geometry,index_right,estacion,Decision,param,value,unit,depth,granularidad,fuente,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
fecha,,,,,,,,,,,,,,,,,,,,,
2017-07-04 09:03:00,POINT (608644.563 6390123.956),1006,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,26095.0,TACUAREMBÓ,CloA_(lab),µg/L,<LC,0.600,1.5,<LC