In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
oan = gpd.read_file("../data/data/oan/oan_registros_clean.geojson")
chla_gems = gpd.read_file("../data/data/joins/gems_chla.geojson")
gem_puntos_examin = pd.read_csv("../data/data/puntos_examinados.csv")

In [3]:
oan["fuente"] = "OAN"
chla_gems ["fuente"] = "GEMS"
oan = oan.rename(columns={"fecha_hora": "fecha"})

In [4]:
gem_puntos_examin.head()

,nombre,Decision,Fecha,Width,Resolution,geometry
0,URY00006,si,2025-02-13 13:52:11.656000,0.05,10,POINT (-55.3727 -34.5071)
1,URY00007,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2762 -34.391)
2,URY00008,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2061 -34.4204)
3,URY00009,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2471 -34.3791)
4,URY00010,dudoso,2025-02-13 13:51:57.401000,0.05,10,POINT (-55.2317 -34.3828)

In [5]:
chla_gems.shape

(3796, 10)

In [6]:
chla_gems = chla_gems[pd.to_datetime(chla_gems["fecha"]).dt.year >= 2017]
chla_gems["fecha"].min()

Timestamp('2017-01-02 00:00:00')

In [7]:
oan_utm  = oan.to_crs(32721).copy()
gems_utm = chla_gems.to_crs(32721).copy()

In [8]:
oan.head()

,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,geometry,fuente
0,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29873.0,RÍO NEGRO,2019-09-05 16:00:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
1,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29985.0,RÍO NEGRO,2019-10-31 09:40:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
2,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31062.0,RÍO NEGRO,2020-06-04 14:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,POINT (-57.41304 -32.9058),OAN
3,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31410.0,RÍO NEGRO,2020-08-06 12:46:00,CloA_(lab),µg/L,33.000000000,0.700000000,2.2,33.000000000,POINT (-57.41304 -32.9058),OAN
4,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31851.0,RÍO NEGRO,2020-11-19 12:29:00,CloA_(lab),µg/L,2.600000000,0.700000000,2.2,2.600000000,POINT (-57.41304 -32.9058),OAN

In [9]:
oan_utm.head()
casos = ["<0.1", "<0.5", "<1", "<1.0", "<1.00", "<LC", "<LD", "LD<X<LC", "LD<x<LC"]
datos = oan[oan["valor_transformado"].isin(casos)]
#puntos_upm2 = OAN_registros_clean[OAN_registros_clean["nombre_programa_x"] == "Agua UPM2 Empresa"]

In [10]:
datos.shape

(1795, 14)

In [11]:
#for  valor in sorted(oan["valor_transformado"].unique(), key=str):
#    print(valor)

In [12]:
oan

,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,geometry,fuente
0,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29873.0,RÍO NEGRO,2019-09-05 16:00:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
1,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,29985.0,RÍO NEGRO,2019-10-31 09:40:00,CloA_(lab),µg/L,LD<x<LC,0.700000000,2.2,LD<x<LC,POINT (-57.41304 -32.9058),OAN
2,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31062.0,RÍO NEGRO,2020-06-04 14:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,POINT (-57.41304 -32.9058),OAN
3,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31410.0,RÍO NEGRO,2020-08-06 12:46:00,CloA_(lab),µg/L,33.000000000,0.700000000,2.2,33.000000000,POINT (-57.41304 -32.9058),OAN
4,Agua Arroyo Grande del Norte DCA,XGRN100.S,100626,31851.0,RÍO NEGRO,2020-11-19 12:29:00,CloA_(lab),µg/L,2.600000000,0.700000000,2.2,2.600000000,POINT (-57.41304 -32.9058),OAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5181,Playa,01SI,100803,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.52111 -32.81884),OAN
5182,Playa,01CU,100804,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.52502 -32.81838),OAN
5183,Playa,01PN,100806,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-56.53247 -32.81044),OAN
5184,Playa,07PV,100709,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-58.1489 -32.6381),OAN
5185,Playa,01BI,100791,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-55.96207 -31.66785),OAN

In [13]:
iguales = gpd.sjoin_nearest(
    gems_utm, oan_utm,
    how='inner',
    max_distance=0.1,
    distance_col='dist'
)

In [14]:
gems_stations = gems_utm["geometry"].unique()
oan_stations = oan_utm["geometry"].unique()

In [15]:
gems_stations = gpd.GeoDataFrame(
    geometry=gems_utm["geometry"].unique(),
    crs=gems_utm.crs,
)
oan_stations = gpd.GeoDataFrame(
    geometry = oan_utm["geometry"].unique(),
    crs = oan_utm.crs
)

In [16]:
iguales = gpd.sjoin_nearest(
    gems_stations, oan_stations,
    how='inner',
    max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
    distance_col='dist'
)
iguales = iguales.drop(columns=["index_right", "dist"])

In [17]:
iguales.shape

(150, 1)

Esto nos dice que tanto en los registros de OAN como en los de Gems, existen estaciones que son identicas.

Lo que no significa que sean las mismas mediciones ni los mismos dias, eso es algo que tenemos que comprobar todavia.

Pero puede ser que estos datos sean compartidos entre ambas organizaciones.

In [18]:
iguales.head(5)

                         geometry
0  POINT (649386.009 6180413.463)
1  POINT (664852.016 6189770.245)
2  POINT (570470.059 6220119.303)
3  POINT (581348.445 6603897.643)
4  POINT (560699.232 6625269.716)

In [19]:
p1 = iguales.iloc[[0]]
p1

                         geometry
0  POINT (649386.009 6180413.463)

In [20]:
chla_p1_gems = gpd.sjoin_nearest(
    p1, gems_utm,
    how='inner',
    max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
    distance_col='dist'
)

In [21]:
chla_p1_gems.head()

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0,mg/l,0.3,DIA,GEMS,0.0

In [22]:
OAN_p1_chla = gpd.sjoin_nearest(
    p1, oan_utm,
    how='inner',
    max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
    distance_col='dist'
)

In [23]:
OAN_p1_chla.head()

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
0,POINT (649386.009 6180413.463),5149,Playa,08AB,100012,1.0,LAVALLEJA,2018-11-12 23:20:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

In [24]:
def examinar_punto(p):
    chla_p_gems = gpd.sjoin_nearest(
        p, gems_utm,
        how='inner',
        max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
        distance_col='dist'
    ) 

    OAN_p_chla = gpd.sjoin_nearest(
        p, oan_utm,
        how='inner',
        max_distance=0.1,       # in the CRS units — meters here, since you're in UTM
        distance_col='dist'
    )
    
    display(chla_p_gems)
    display(OAN_p_chla)

In [25]:
examinar_punto(p1)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,2018-11-12 23:20:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
0,POINT (649386.009 6180413.463),5149,Playa,08AB,100012,1.0,LAVALLEJA,2018-11-12 23:20:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

In [26]:
p2 = iguales.iloc[[1]]
examinar_punto(p2)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
1,POINT (664852.016 6189770.245),1,URY00008,dudoso,Chl-a,2018-11-12 08:30:00,0.0,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
1,POINT (664852.016 6189770.245),5121,Playa,06SF,100014,0.0,LAVALLEJA,2018-11-12 08:30:00,CloA_(lab),µg/L,0.000,NaN,NaN,0.000,OAN,0.0

In [27]:
p3 = iguales.iloc[[2]]
examinar_punto(p3)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
2,POINT (570470.059 6220119.303),6,URY00029,si,Chl-a,2017-02-22 11:00:00,0.0004,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),7,URY00029,si,Chl-a,2017-04-19 13:00:00,0.0007,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),8,URY00029,si,Chl-a,2017-12-13 11:44:00,0.0286,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),9,URY00029,si,Chl-a,2018-02-21 11:15:00,0.0049,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),10,URY00029,si,Chl-a,2018-10-17 11:43:00,0.0025,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),11,URY00029,si,Chl-a,2019-04-24 11:00:00,0.0023,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),20,URY00029,si,Chl-a,2022-10-19 11:26:00,0.0071,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),19,URY00029,si,Chl-a,2022-08-31 11:09:00,0.0096,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),18,URY00029,si,Chl-a,2022-02-22 13:37:00,0.0067,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),17,URY00029,si,Chl-a,2021-12-15 11:00:00,0.0740,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),16,URY00029,si,Chl-a,2020-12-09 10:50:00,0.0070,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),15,URY00029,si,Chl-a,2020-10-14 11:27:00,0.0033,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),14,URY00029,si,Chl-a,2020-08-12 11:42:00,0.0028,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),21,URY00029,si,Chl-a,2022-12-21 10:46:00,0.0180,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),13,URY00029,si,Chl-a,2020-02-18 11:10:00,0.0062,mg/l,0.3,DIA,GEMS,0.0
2,POINT (570470.059 6220119.303),12,URY00029,si,Chl-a,2019-12-11 10:50:00,0.0840,mg/l,0.3,DIA,GEMS,0.0

,geometry,index_right,nombre_programa,estacion,id_estacion,nro_muestra,departamento,fecha,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado,fuente,dist
2,POINT (570470.059 6220119.303),1734,Agua rio Santa Lucia DCA,XSLH030.S,100201,26596.0,FLORIDA,2017-10-18 11:58:00,CloA_(lab),µg/L,<LC,0.600,1.5,<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1733,Agua rio Santa Lucia DCA,XSLH030.S,100201,26124.0,FLORIDA,2017-06-21 11:05:00,CloA_(lab),µg/L,<LD,0.600,1.5,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1745,Agua rio Santa Lucia DCA,XSLH030.S,100201,29435.0,FLORIDA,2019-06-12 11:15:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1771,Agua rio Santa Lucia DCA,XSLH030.S,100201,37542.0,FLORIDA,2024-06-04 12:19:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1772,Agua rio Santa Lucia DCA,XSLH030.S,100201,37767.0,FLORIDA,2024-08-13 10:41:00,CloA_(lab),µg/L,3.500000000,0.700000000,2.2,3.500000000,OAN,0.0
2,POINT (570470.059 6220119.303),1773,Agua rio Santa Lucia DCA,XSLH030.S,100201,38119.0,FLORIDA,2024-10-22 12:00:00,CloA_(lab),µg/L,11.000000000,0.700000000,2.2,11.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1774,Agua rio Santa Lucia DCA,XSLH030.S,100201,38432.0,FLORIDA,2024-12-10 11:49:00,CloA_(lab),µg/L,2.400000000,0.700000000,2.2,2.400000000,OAN,0.0
2,POINT (570470.059 6220119.303),1769,Agua rio Santa Lucia DCA,XSLH030.S,100201,36953.0,FLORIDA,2024-02-06 11:56:00,CloA_(lab),µg/L,7.900000000,0.700000000,2.2,7.900000000,OAN,0.0
2,POINT (570470.059 6220119.303),1753,Agua rio Santa Lucia DCA,XSLH030.S,100201,31429.0,FLORIDA,2020-08-12 11:42:00,CloA_(lab),µg/L,2.800000000,0.700000000,2.2,2.800000000,OAN,0.0
2,POINT (570470.059 6220119.303),1767,Agua rio Santa Lucia DCA,XSLH030.S,100201,36744.0,FLORIDA,2023-12-13 09:20:00,CloA_(lab),µg/L,2.200000000,0.700000000,2.2,2.200000000,OAN,0.0
2,POINT (570470.059 6220119.303),1735,Agua rio Santa Lucia DCA,XSLH030.S,100201,26859.0,FLORIDA,2017-12-13 11:44:00,CloA_(lab),µg/L,28.600,0.100,0.1,28.600,OAN,0.0
2,POINT (570470.059 6220119.303),1743,Agua rio Santa Lucia DCA,XSLH030.S,100201,27919.0,FLORIDA,2018-08-15 11:59:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1742,Agua rio Santa Lucia DCA,XSLH030.S,100201,28894.0,FLORIDA,2019-02-20 12:10:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1741,Agua rio Santa Lucia DCA,XSLH030.S,100201,28606.0,FLORIDA,2018-12-12 11:24:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1740,Agua rio Santa Lucia DCA,XSLH030.S,100201,28336.0,FLORIDA,2018-10-17 11:43:00,CloA_(lab),µg/L,2.500,0.700,2.2,2.500,OAN,0.0
2,POINT (570470.059 6220119.303),1739,Agua rio Santa Lucia DCA,XSLH030.S,100201,27211.0,FLORIDA,2018-02-21 11:15:00,CloA_(lab),µg/L,4.900,0.700,2.2,4.900,OAN,0.0
2,POINT (570470.059 6220119.303),1738,Agua rio Santa Lucia DCA,XSLH030.S,100201,27710.0,FLORIDA,2018-06-13 11:20:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1737,Agua rio Santa Lucia DCA,XSLH030.S,100201,25907.0,FLORIDA,2017-04-19 13:00:00,CloA_(lab),µg/L,0.700,NaN,0.1,0.700,OAN,0.0
2,POINT (570470.059 6220119.303),1736,Agua rio Santa Lucia DCA,XSLH030.S,100201,25650.0,FLORIDA,2017-02-22 11:00:00,CloA_(lab),µg/L,0.400,NaN,0.1,0.400,OAN,0.0
2,POINT (570470.059 6220119.303),1744,Agua rio Santa Lucia DCA,XSLH030.S,100201,29219.0,FLORIDA,2019-04-24 11:00:00,CloA_(lab),µg/L,2.300,0.700,2.2,2.300,OAN,0.0
2,POINT (570470.059 6220119.303),1747,Agua rio Santa Lucia DCA,XSLH030.S,100201,30029.0,FLORIDA,2019-10-23 11:30:00,CloA_(lab),µg/L,<LD,0.700,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1746,Agua rio Santa Lucia DCA,XSLH030.S,100201,29730.0,FLORIDA,2019-08-14 11:20:00,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1759,Agua rio Santa Lucia DCA,XSLH030.S,100201,33276.0,FLORIDA,2021-12-15 11:00:00,CloA_(lab),µg/L,74.000000000,0.700000000,2.2,74.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1766,Agua rio Santa Lucia DCA,XSLH030.S,100201,35563.0,FLORIDA,2023-02-14 11:03:00,CloA_(lab),µg/L,22.000000000,0.700000000,2.2,22.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1768,Agua rio Santa Lucia DCA,XSLH030.S,100201,36535.0,FLORIDA,2023-10-18 11:55:00,CloA_(lab),µg/L,9.100000000,0.700000000,2.2,9.100000000,OAN,0.0
2,POINT (570470.059 6220119.303),1760,Agua rio Santa Lucia DCA,XSLH030.S,100201,33622.0,FLORIDA,2022-02-22 13:37:00,CloA_(lab),µg/L,6.700000000,0.700000000,2.2,6.700000000,OAN,0.0
2,POINT (570470.059 6220119.303),1758,Agua rio Santa Lucia DCA,XSLH030.S,100201,32954.0,FLORIDA,2021-10-13 10:38:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1761,Agua rio Santa Lucia DCA,XSLH030.S,100201,33871.0,FLORIDA,2022-04-20 11:10:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1762,Agua rio Santa Lucia DCA,XSLH030.S,100201,34685.0,FLORIDA,2022-08-31 11:09:00,CloA_(lab),µg/L,9.600000000,0.700000000,2.2,9.600000000,OAN,0.0
2,POINT (570470.059 6220119.303),1763,Agua rio Santa Lucia DCA,XSLH030.S,100201,34914.0,FLORIDA,2022-10-19 11:26:00,CloA_(lab),µg/L,7.100000000,0.700000000,2.2,7.100000000,OAN,0.0
2,POINT (570470.059 6220119.303),1764,Agua rio Santa Lucia DCA,XSLH030.S,100201,35412.0,FLORIDA,2022-12-21 10:46:00,CloA_(lab),µg/L,18.000000000,0.700000000,2.2,18.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1765,Agua rio Santa Lucia DCA,XSLH030.S,100201,36337.0,FLORIDA,2023-08-30 00:00:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1757,Agua rio Santa Lucia DCA,XSLH030.S,100201,32451.0,FLORIDA,2021-07-28 10:52:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1756,Agua rio Santa Lucia DCA,XSLH030.S,100201,32744.0,FLORIDA,2021-09-01 11:20:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1755,Agua rio Santa Lucia DCA,XSLH030.S,100201,32001.0,FLORIDA,2020-12-09 10:50:00,CloA_(lab),µg/L,7.000000000,0.700000000,2.2,7.000000000,OAN,0.0
2,POINT (570470.059 6220119.303),1754,Agua rio Santa Lucia DCA,XSLH030.S,100201,31660.0,FLORIDA,2020-10-14 11:27:00,CloA_(lab),µg/L,3.300000000,0.700000000,2.2,3.300000000,OAN,0.0
2,POINT (570470.059 6220119.303),1770,Agua rio Santa Lucia DCA,XSLH030.S,100201,37288.0,FLORIDA,2024-04-02 09:57:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1752,Agua rio Santa Lucia DCA,XSLH030.S,100201,31090.0,FLORIDA,2020-06-10 11:30:00,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC,OAN,0.0
2,POINT (570470.059 6220119.303),1751,Agua rio Santa Lucia DCA,XSLH030.S,100201,26418.0,FLORIDA,2017-08-16 11:27:00,CloA_(lab),µg/L,<LD,0.600000000,1.5,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1750,Agua rio Santa Lucia DCA,XSLH030.S,100201,30985.0,FLORIDA,2020-04-28 11:25:00,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD,OAN,0.0
2,POINT (570470.059 6220119.303),1749,Agua rio Santa Lucia DCA,XSLH030.S,100201,30590.0,FLORIDA,2020-02-18 11:10:00,CloA_(lab),µg/L,6.200000000,0.700000000,2.2,6.200000000,OAN,0.0
2,POINT (570470.059 6220119.303),1748,Agua rio Santa Lucia DCA,XSLH030.S,100201,30283.0,FLORIDA,2019-12-11 10:50:00,CloA_(lab),µg/L,84.000,0.700,2.2,84.000,OAN,0.0

#### Que queremos?
0. 'iguales' es una lista de puntos que aparecen repetidos tanto en la fuente OAN como Gems (datos compartidos entre ambas organizaciones?)
1. Para cualquier punto p de 'iguales' lo que queremos es:
2. obtener los registros para ese mismo punto de oan y gems
3. concatenear esos registros para tener un unico dataframe
4. Eliminar duplicados: Es duplicado si 1) la medicion fue tomada en la misma fecha y el valor es el mismo (o la diferencia es despreciable)

In [28]:
iguales

                           geometry
0    POINT (649386.009 6180413.463)
1    POINT (664852.016 6189770.245)
2    POINT (570470.059 6220119.303)
3    POINT (581348.445 6603897.643)
4    POINT (560699.232 6625269.716)
..                              ...
147  POINT (518553.944 6362768.507)
148  POINT (518472.926 6362066.591)
149  POINT (697634.803 6136124.084)
150  POINT (716874.108 6144491.973)
151   POINT (600108.84 6489773.595)

[150 rows x 1 columns]

In [29]:
p = iguales.iloc[[32]]
p##?
#JOIN PUNTOS == OAN.PUNTOS == GEMS.PUNTOS 
#
#[p1, chla_oan, chla_gems]
#[p1, chla_oan, chla_gems]
#[p1, chla_oan, chla_gems]
#[p1, chla_oan, chla_gems]
#...
#[p2, chla_oan, chla_gems]
#[p2, chla_oan, chla_gems]
#[p2, chla_oan, chla_gems]
#[p2, chla_oan, chla_gems]
#...
#[pn, chla_oan, chla_gems]
#[pn, chla_oan, chla_gems]
#[pn, chla_oan, chla_gems]
#[pn, chla_oan, chla_gems]
#...
#

                          geometry
32  POINT (608644.563 6390123.956)

In [30]:
chla_p_gems = gpd.sjoin_nearest(
    p, gems_utm,
    how='inner',
    max_distance=0.1,
    distance_col='dist'
)

chla_p_oan = gpd.sjoin_nearest(
    p, oan_utm,
    how='inner',
    max_distance=0.1,
    distance_col='dist'
)

In [31]:
chla_p_gems.head(1)

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,fuente,dist
32,POINT (608644.563 6390123.956),556,URY00071,si,Chl-a,2022-11-15 13:50:00,0.0033,mg/l,0.3,DIA,GEMS,0.0

In [32]:
mediciones_de_p = gpd.GeoDataFrame(
    pd.concat([chla_p_gems, chla_p_oan], ignore_index=True),
    geometry = "geometry",
    crs= oan_utm.crs
)

In [33]:
mediciones_de_p.head()

,geometry,index_right,estacion,Decision,param,fecha,value,unit,depth,granularidad,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
0,POINT (608644.563 6390123.956),556,URY00071,si,Chl-a,2022-11-15 13:50:00,0.0033,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,POINT (608644.563 6390123.956),553,URY00071,si,Chl-a,2021-03-09 13:07:00,0.0077,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,POINT (608644.563 6390123.956),545,URY00071,si,Chl-a,2018-01-16 13:28:00,0.0042,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,POINT (608644.563 6390123.956),546,URY00071,si,Chl-a,2018-04-10 14:20:00,0.0032,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,POINT (608644.563 6390123.956),547,URY00071,si,Chl-a,2018-09-25 13:30:00,0.0023,mg/l,0.3,DIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Que queremos filtrar ahora?
En el paso anterior lo que hicimos fue filtrar todos los puntos que aparecen en ambas fuentes: OAN y Gems

1. Para cada punto queremos saber que mediciones estan repetidas
2. Una medicion puede estar repitidia si: Fue tomadad en la misma fecha y si el valor es el mismo

In [34]:
mediciones_de_p = mediciones_de_p.set_index("fecha").sort_index()

In [35]:
mediciones_de_p.shape

(37, 21)

In [36]:
N = mediciones_de_p.shape[0]
eps = 1e-5

def fila_extraer_chla(fila, chla_gems_fallback):
    if fila["fuente"] == "GEMS":
        chla = float(fila["value"])
    elif fila["fuente"] == "OAN":
        if fila["valor_transformado"] in casos:
            chla = chla_gems_fallback
        else:
            chla = float(fila["valor_transformado"]) / 1000
    return chla

filas_finales = []
i = 0
ultimo_igual = False
while i < N - 1:
    fecha1 = mediciones_de_p.index[i]
    fecha2 = mediciones_de_p.index[i+1]
    if fecha1 == fecha2:
        print("IGUALES!")
        fila1 = mediciones_de_p.iloc[i]
        fila2 = mediciones_de_p.iloc[i+1]

        if fila1["fuente"] == "GEMS":
            chla_gems = float(fila1["value"])
        else:
            chla_gems = float(fila2["value"])

        chla_f1 = fila_extraer_chla(fila1, chla_gems)
        chla_f2 = fila_extraer_chla(fila2, chla_gems)
        diff = abs(chla_f1 - chla_f2)
        if diff <= eps:
            # GUARDAR UNO SOLO!
            print(chla_f1, chla_f2, "Igual valor")
            filas_finales.append(fila1)
        else:
            print(chla_f1, chla_f2, "Diferente valor")
            filas_finales.append(fila1)
            filas_finales.append(fila2)
        i+=2
        if i == N:
            ultimo_igual = True
    else:
        print("fechas differentes!")
        filas_finales.append(mediciones_de_p.iloc[i])
        i+=1

if not ultimo_igual and N > 0:
    filas_finales.append(mediciones_de_p.iloc[N-1])

mediciones_de_p_sinrep = gpd.GeoDataFrame(pd.DataFrame(filas_finales), geometry="geometry", crs=mediciones_de_p.crs)

fechas differentes!
fechas differentes!
IGUALES!
0.0041999998502433 0.004200000000000001 Igual valor
IGUALES!
0.0032 0.0031999999191612 Igual valor
fechas differentes!
IGUALES!
0.0023000000510364 0.0023 Igual valor
IGUALES!
0.003000000026077 0.003 Igual valor
IGUALES!
0.0025 0.0024999999441206 Igual valor
fechas differentes!
IGUALES!
0.006000000052154 0.006 Igual valor
IGUALES!
0.0063000000081956 0.0063 Igual valor
fechas differentes!
fechas differentes!
IGUALES!
0.0149999996647238 0.015 Igual valor
IGUALES!
0.0076999999582767 0.0077 Igual valor
fechas differentes!
IGUALES!
0.0057999999262392 0.0058 Igual valor
IGUALES!
0.0099999997764825 0.01 Igual valor
fechas differentes!
fechas differentes!
IGUALES!
0.0033 0.0032999999821186 Igual valor
fechas differentes!
fechas differentes!
fechas differentes!

In [37]:
mediciones_de_p_sinrep

,geometry,index_right,estacion,Decision,param,value,unit,depth,granularidad,fuente,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
2017-07-04 09:03:00,POINT (608644.563 6390123.956),1006,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,26095.0,TACUAREMBÓ,CloA_(lab),µg/L,<LC,0.600,1.5,<LC
2017-10-03 13:08:00,POINT (608644.563 6390123.956),1007,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,26553.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC
2018-01-16 13:28:00,POINT (608644.563 6390123.956),545,URY00071,si,Chl-a,0.0042,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-10 14:20:00,POINT (608644.563 6390123.956),1009,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,27421.0,TACUAREMBÓ,CloA_(lab),µg/L,3.200,0.700,2.2,3.200
2018-07-03 13:30:00,POINT (608644.563 6390123.956),1005,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,27867.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<x<LC,0.700,2.2,LD<x<LC
2018-09-25 13:30:00,POINT (608644.563 6390123.956),547,URY00071,si,Chl-a,0.0023,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-16 11:30:00,POINT (608644.563 6390123.956),548,URY00071,si,Chl-a,0.0030,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-19 14:20:00,POINT (608644.563 6390123.956),1012,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,29160.0,TACUAREMBÓ,CloA_(lab),µg/L,2.500,0.700,2.2,2.500
2019-06-26 10:28:00,POINT (608644.563 6390123.956),1013,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,29581.0,TACUAREMBÓ,CloA_(lab),µg/L,<LD,0.700,2.2,<LD
2019-10-08 12:53:00,POINT (608644.563 6390123.956),550,URY00071,si,Chl-a,0.0060,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-28 14:12:00,POINT (608644.563 6390123.956),551,URY00071,si,Chl-a,0.0063,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-05-05 13:21:00,POINT (608644.563 6390123.956),1016,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,30834.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
2020-06-23 14:59:00,POINT (608644.563 6390123.956),1018,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,31158.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
2020-09-29 14:35:00,POINT (608644.563 6390123.956),552,URY00071,si,Chl-a,0.0150,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-09 13:07:00,POINT (608644.563 6390123.956),553,URY00071,si,Chl-a,0.0077,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-07 13:22:00,POINT (608644.563 6390123.956),1020,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,32827.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
2021-11-30 13:00:00,POINT (608644.563 6390123.956),554,URY00071,si,Chl-a,0.0058,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-18 14:19:00,POINT (608644.563 6390123.956),555,URY00071,si,Chl-a,0.0100,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-04-26 13:30:00,POINT (608644.563 6390123.956),1023,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,33926.0,TACUAREMBÓ,CloA_(lab),µg/L,<LD,0.700000000,2.2,<LD
2022-08-02 13:50:00,POINT (608644.563 6390123.956),1024,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,34334.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
2022-11-15 13:50:00,POINT (608644.563 6390123.956),1025,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,35111.0,TACUAREMBÓ,CloA_(lab),µg/L,3.300000000,0.700000000,2.2,3.300000000
2023-01-24 13:45:00,POINT (608644.563 6390123.956),1026,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,35475.0,TACUAREMBÓ,CloA_(lab),µg/L,790.000000000,0.700000000,2.2,790.000000000
2023-08-08 13:21:00,POINT (608644.563 6390123.956),1027,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,36259.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
2023-11-07 15:42:00,POINT (608644.563 6390123.956),1028,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,36615.0,TACUAREMBÓ,CloA_(lab),µg/L,6.200000000,0.700000000,2.2,6.200000000
2024-01-16 12:31:00,POINT (608644.563 6390123.956),1029,ERDB030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Negro DCA,100256.0,36881.0,TACUAREMBÓ,CloA_(lab),µg/L,15.000000000,0.700000000,2.2,15.000000000

#### Ahora para todos los puntos
Generalizamos lo anterior: en vez de un solo punto `p`, iteramos sobre todos los puntos de `iguales` y deduplicamos cada uno.

In [38]:
def procesar_punto(p):
    chla_p_gems = gpd.sjoin_nearest(
        p, gems_utm,
        how='inner',
        max_distance=0.1,
        distance_col='dist'
    )

    chla_p_oan = gpd.sjoin_nearest(
        p, oan_utm,
        how='inner',
        max_distance=0.1,
        distance_col='dist'
    )

    mediciones_de_p = gpd.GeoDataFrame(
        pd.concat([chla_p_gems, chla_p_oan], ignore_index=True),
        geometry="geometry",
        crs=oan_utm.crs
    )
    mediciones_de_p = mediciones_de_p.set_index("fecha").sort_index()

    N = mediciones_de_p.shape[0]
    eps = 1e-5

    def fila_extraer_chla(fila, chla_gems_fallback):
        if fila["fuente"] == "GEMS":
            chla = float(fila["value"])
        elif fila["fuente"] == "OAN":
            if fila["valor_transformado"] in casos:
                chla = chla_gems_fallback
            else:
                chla = float(fila["valor_transformado"]) / 1000
        return chla

    filas_finales = []
    i = 0
    ultimo_igual = False
    while i < N - 1:
        fecha1 = mediciones_de_p.index[i]
        fecha2 = mediciones_de_p.index[i+1]
        if fecha1 == fecha2:
            fila1 = mediciones_de_p.iloc[i]
            fila2 = mediciones_de_p.iloc[i+1]

            if fila1["fuente"] == "GEMS":
                chla_gems = float(fila1["value"])
            else:
                chla_gems = float(fila2["value"])

            chla_f1 = fila_extraer_chla(fila1, chla_gems)
            chla_f2 = fila_extraer_chla(fila2, chla_gems)
            diff = abs(chla_f1 - chla_f2)
            if diff <= eps:
                # GUARDAR UNO SOLO!
                filas_finales.append(fila1)
            else:
                filas_finales.append(fila1)
                filas_finales.append(fila2)
            i+=2
            if i == N:
                ultimo_igual = True
        else:
            filas_finales.append(mediciones_de_p.iloc[i])
            i+=1

    if not ultimo_igual and N > 0:
        filas_finales.append(mediciones_de_p.iloc[N-1])

    mediciones_de_p_sinrep = gpd.GeoDataFrame(pd.DataFrame(filas_finales), geometry="geometry", crs=mediciones_de_p.crs)

    return N, mediciones_de_p_sinrep

In [39]:
resultados = []
total_in = 0

for idx in range(len(iguales)):
    p = iguales.iloc[[idx]]
    N, mediciones_de_p_sinrep = procesar_punto(p)
    total_in += N
    resultados.append(mediciones_de_p_sinrep)

todas_mediciones_sinrep = gpd.GeoDataFrame(pd.concat(resultados, ignore_index=True), geometry="geometry", crs=oan_utm.crs)

In [40]:
todas_mediciones_sinrep

,geometry,index_right,estacion,Decision,param,value,unit,depth,granularidad,fuente,...,nombre_programa,id_estacion,nro_muestra,departamento,nombre_clave,uni_nombre,valor_original,limite_deteccion,limite_cuantificacion,valor_transformado
0,POINT (649386.009 6180413.463),0,URY00006,si,Chl-a,0.0000,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,POINT (664852.016 6189770.245),1,URY00008,dudoso,Chl-a,0.0000,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,POINT (570470.059 6220119.303),6,URY00029,si,Chl-a,0.0004,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,POINT (570470.059 6220119.303),7,URY00029,si,Chl-a,0.0007,mg/l,0.3,DIA,GEMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,POINT (570470.059 6220119.303),1733,XSLH030.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Santa Lucia DCA,100201.0,26124.0,FLORIDA,CloA_(lab),µg/L,<LD,0.600,1.5,<LD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5731,POINT (600108.84 6489773.595),1807,XTAH013.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Tacuarembo DCA,100731.0,36567.0,TACUAREMBÓ,CloA_(lab),µg/L,9.800000000,0.700000000,2.2,9.800000000
5732,POINT (600108.84 6489773.595),1808,XTAH013.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Tacuarembo DCA,100731.0,37061.0,TACUAREMBÓ,CloA_(lab),µg/L,5.900000000,0.700000000,2.2,5.900000000
5733,POINT (600108.84 6489773.595),1809,XTAH013.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Tacuarembo DCA,100731.0,37441.0,TACUAREMBÓ,CloA_(lab),µg/L,3.300000000,0.700000000,2.2,3.300000000
5734,POINT (600108.84 6489773.595),1810,XTAH013.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Tacuarembo DCA,100731.0,37795.0,TACUAREMBÓ,CloA_(lab),µg/L,LD<X<LC,0.700000000,2.2,LD<X<LC
5735,POINT (600108.84 6489773.595),1811,XTAH013.S,NaN,NaN,NaN,NaN,NaN,NaN,OAN,...,Agua rio Tacuarembo DCA,100731.0,38326.0,TACUAREMBÓ,CloA_(lab),µg/L,4.900000000,0.700000000,2.2,4.900000000

In [41]:
total_sin_dedup = total_in
total_con_dedup = todas_mediciones_sinrep.shape[0]

print("Mediciones OAN + GEMS sin deduplicar (puntos compartidos):", total_sin_dedup)
print("Mediciones despues de deduplicar:", total_con_dedup)
print("Duplicados eliminados:", total_sin_dedup - total_con_dedup)

Mediciones OAN + GEMS sin deduplicar (puntos compartidos): 7323
Mediciones despues de deduplicar: 5736
Duplicados eliminados: 1587

In [46]:
todas_mediciones_sinrep.shape

(5736, 21)

In [48]:
todas_mediciones_sinrep.to_file("../data/data/chla_oan_gems_dedup.geojson", driver="GeoJSON")