In [1]:
import pandas as pd

In [2]:
data_set = pd.read_csv("../../data/dataset_final/indices_acolite.csv")
print(data_set.shape)
data_set.head()

(2957, 60)

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
0,0,2017-01-02 00:00:00,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.072809,-34.205076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
1,1,2017-01-02 00:00:00,GEMS,6.8,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.050169,-34.795008,...,0.913862,0.914237,0.020905,0.015930,0.011604,0.011688,0.000858,0.000585,False,False
2,2,2017-01-02 00:00:00,GEMS,3.2,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.042069,-34.829733,...,0.902174,0.904781,0.018551,0.016533,0.010629,0.010657,0.001456,0.000866,False,False
3,3,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.061691,-34.242904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
4,4,2017-01-02 00:00:00,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.068754,-34.219198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [3]:
sin_imagen = data_set[data_set["B02_mean"].isna()].copy()
print(sin_imagen.shape)
sin_imagen.head()

(1621, 60)

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
0,0,2017-01-02 00:00:00,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.072809,-34.205076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
3,3,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.061691,-34.242904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
4,4,2017-01-02 00:00:00,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.068754,-34.219198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
7,7,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.057434,-34.243699,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
8,8,2017-01-02 00:00:00,GEMS,5.9,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.078086,-34.764606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [15]:
con_imagen = data_set[data_set["B02_mean"].notna()].copy()
con_imagen.head()

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
1,1,2017-01-02 00:00:00,GEMS,6.8,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.050169,-34.795008,...,0.913862,0.914237,0.020905,0.015930,0.011604,0.011688,0.000858,0.000585,False,False
2,2,2017-01-02 00:00:00,GEMS,3.2,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.042069,-34.829733,...,0.902174,0.904781,0.018551,0.016533,0.010629,0.010657,0.001456,0.000866,False,False
5,5,2017-01-02 00:00:00,GEMS,5.9,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.068342,-34.841008,...,0.911265,0.908359,0.016059,0.012848,0.011602,0.011753,0.000977,0.000617,False,False
6,6,2017-01-02 00:00:00,GEMS,11.4,LDS,M,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.143344,-34.842672,...,1.644557,1.647732,0.125156,0.087272,0.002934,0.002866,0.001276,0.000746,False,False
9,9,2017-01-02 00:00:00,GEMS,6.4,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.120006,-34.843169,...,1.174755,1.171955,0.033976,0.020926,0.007152,0.007324,0.000830,0.000636,False,False

In [14]:
con_imagen_40 = con_imagen.sample(40, random_state=42).copy()
con_imagen_40.head()

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
2050,2050,2022-12-05 11:24:00,GEMS,0.40,LDS,U,S2B_MSIL1C_20221206T133829_N0510_R124_T21HXB_2...,1 days 02:14:29,-55.143344,-34.842672,...,1.654287,1.659302,0.117248,0.094029,0.001286,0.001349,0.000813,0.000819,False,False
2396,2396,2023-05-08 10:25:00,GEMS,3.00,RN-UPM2,O,S2A_MSIL1C_20230510T133831_N0510_R124_T21HWD_2...,2 days 03:13:31,-56.570172,-32.840639,...,0.934829,0.934359,0.034106,0.022370,0.012195,0.012135,0.000901,0.000770,False,False
2743,2743,2025-03-12 15:30:00,OAN,11.80,RN-UPM2,M,S2C_MSIL1C_20250310T133901_N0511_R124_T21HWD_2...,2 days 01:50:59,-56.438833,-32.828861,...,1.295386,1.292451,0.038099,0.032948,0.003880,0.003865,0.000692,0.000649,False,False
704,704,2020-01-24 11:48:00,GEMS,16.50,LDS,M,S2A_MSIL1C_20200123T133221_N0500_R081_T21HXB_2...,0 days 22:15:39,-55.120006,-34.843169,...,1.787833,1.808827,0.117759,0.150375,0.002032,0.002062,0.000533,0.000591,False,False
519,519,2019-02-07 00:00:00,GEMS,7.56,LDS,O,S2A_MSIL1C_20190207T133221_N0500_R081_T21HXB_2...,0 days 13:32:21,-55.143344,-34.842672,...,1.812645,1.832354,1.019992,0.626178,0.001440,0.003794,0.009799,0.005401,False,False

In [6]:
sin_imagen.groupby("estado_trofico").size()

estado_trofico
E     56
M    249
O    823
U    493
dtype: int64

In [ ]:
sin_imagen_e = sin_imagen[sin_imagen["estado_trofico"] == "E"].copy()
sin_imagen_e.head()

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
193,193,2017-07-31 00:00:00,GEMS,37.000000,LDS,E,S2A_MSIL1C_20170727T133231_N0500_R081_T21HXB_2...,3 days 10:27:29,-55.042069,-34.829733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
395,395,2018-04-12 11:26:00,OAN,31.000000,RN-UPM2,E,S2B_MSIL1C_20180411T134209_N0500_R124_T21HWD_2...,0 days 21:43:51,-56.798615,-32.876116,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
659,659,2020-01-04 14:00:00,OAN,37.100000,LDS,E,S2A_MSIL1C_20200103T133221_N0500_R081_T21HXB_2...,1 days 00:27:39,-55.042069,-34.829733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
660,660,2020-01-06 15:00:00,GEMS,44.500001,LDS,E,S2A_MSIL1C_20200106T134211_N0500_R124_T21HXB_2...,0 days 01:17:49,-55.042069,-34.829733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
661,661,2020-01-07 06:05:00,GEMS,55.900000,LDS,E,S2A_MSIL1C_20200106T134211_N0500_R124_T21HXB_2...,0 days 16:22:49,-55.042069,-34.829733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [ ]:
sin_imagen_e_20 = sin_imagen_e.sample(20, random_state=42).copy()
sin_imagen_e_20.head()

(20, 60)

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
193,193,2017-07-31 00:00:00,GEMS,37.000000,LDS,E,S2A_MSIL1C_20170727T133231_N0500_R081_T21HXB_2...,3 days 10:27:29,-55.042069,-34.829733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
691,691,2020-01-16 13:30:00,GEMS,33.500001,LDS,E,S2A_MSIL1C_20200116T134211_N0500_R124_T21HXB_2...,0 days 00:12:11,-55.143344,-34.842672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
2386,2386,2023-04-11 11:00:00,OAN,34.000000,RN-UPM2,E,S2A_MSIL1C_20230410T133841_N0510_R124_T21HWD_2...,0 days 21:21:19,-56.418000,-32.828667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
941,941,2020-12-09 17:10:00,GEMS,54.800000,RN-UPM2,E,S2A_MSIL1C_20201211T134211_N0500_R124_T21HWD_2...,1 days 20:32:11,-56.429528,-32.823805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
1764,1764,2022-04-25 15:45:00,GEMS,26.600000,RN-UPM2,E,S2A_MSIL1C_20220425T134221_N0510_R124_T21HWD_2...,0 days 02:02:39,-56.568167,-32.843667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [ ]:
sin_imagen_otros = sin_imagen[sin_imagen["estado_trofico"] != "E"].copy()
sin_imagen_otros.head()

(1565, 60)

,matchup_index,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,lon,lat,...,green_red_mean,green_red_median,green_red_iqr,green_red_std,mci_mean,mci_median,mci_iqr,mci_std,sin_resultado,pocos_pixeles_buenos
0,0,2017-01-02 00:00:00,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.072809,-34.205076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
3,3,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.061691,-34.242904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
4,4,2017-01-02 00:00:00,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.068754,-34.219198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
7,7,2017-01-02 00:00:00,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52,-58.057434,-34.243699,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True
8,8,2017-01-02 00:00:00,GEMS,5.9,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:38,-55.078086,-34.764606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True

In [ ]:
sin_imagen_otros_20 = sin_imagen_otros.sample(20, random_state=42).copy()
sin_imagen_otros_20.groupby("estado_trofico").size()

(20, 60)

estado_trofico
M     4
O    10
U     6
dtype: int64

In [ ]:
sin_imagen_40 = pd.concat([sin_imagen_e_20, sin_imagen_otros_20], ignore_index=True)
sin_imagen_40.groupby("estado_trofico").size()

(40, 60)

estado_trofico
E    20
M     4
O    10
U     6
dtype: int64

In [12]:
con_datos = con_imagen_40.copy()
con_datos.to_csv("../../data/acolite_prueba/con_datos.csv", index=False)
con_datos.shape

(40, 60)

In [13]:
sin_datos = sin_imagen_40.copy()
sin_datos.to_csv("../../data/acolite_prueba/sin_datos.csv", index=False)
sin_datos.shape

(40, 60)